### ISSUE TITLE
Simplify the interpretation of internal targets by requiring targets to be more explicit

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#106]
Currently, interpreting both "XPATH" and internal (`#...`) targets involves a fair amount of implicit contextual knowledge. XPATHs require knowledge about the "default" attribute of each SED and model language class. This is particularly complicated because it requires knowledge of both SED and model languages. Internal targets require similar implicit contextual knowledge, although not as much as for XPATHs since internal targets are limited to SED (and cannot reference entities in models). The need for this implicit knowledge increases the complexity of implementing SED.

The text of the specifications doesn't prescribe much for internal targets. The precedent for internal targets is largely established in the examples. Here's an excerpt from one of the 4 examples:
```
<vectorRange id="current">
    <value > 1 </value >
    <value > 10 </value >
</ vectorRange >
...
<variable id="val" target="#current" />
```

Interpreting the above example requires the implicit knowledge that `#current` refers to the value of the `VectorRange` with `id` `current` for the current iteration over the master range of their parent repeated task. Because the examples in the specifications only illustrates two cases of internal targets, the implicit conventions for the interpretation of internal targets are not clear.

A couple ways this could be addressed:
- Outline every way that internal targets should be interpreted. However, the specifications would be verbose and this would be just as cumbersome to implement as the current status quo.
- Use more explicit targets as is done in some XPATH examples. For example, instead of `#current` in the sample above, use `#current/@values[taskRangeIndex]`. This requires one special token, `taskRangeIndex`, to be defined that allows references to the current iteration over the main range of a repeated task.

**Comment by luciansmith** [comment]
Given that few if any tools support the actual parsing of XPath, I would not suggest going with option 2, which leaves us with option 1.  Essentially, I think that option 2 would effectively require the addition of explicit explanations anyway, not to mention the fact that interpreters will still have to deal with models that just use #current or what have you.

**Comment by luciansmith** [comment]
Looking into this:

There are exactly two elements in SED-ML that have mathematical meaning and are valid values of a target:  a Range and a DataSource.  The former can only be used in a RepeatedTask, and the latter can be used anywhere in theory, but I think they should be restricted to multidimensional data in DataGenerators, and only scalars elsewhere.  This was very unclear, and figuring it out required flipping back and forth through the spec and thinking about it a lot.  So!  I changed the 'target' section to the following, which hopefully is a lot clearer and more useful:

"The target attribute may also be used in three situations to reference another SED-ML element with
mathematical meaning, by containing a fragment identifier consisting of a hash character (#) followed
by the SId of the element (i.e. \#id001").

The first situation is a Variable inside a RepeatedTask, which may use a target to reference a Range.
In this situation, the Variable has the mathematical meaning of the scalar value of the Range for that
iteration of the RepeatedTask.

The second situation is that any Variable may use a target to reference a scalar DataSource. In this
situation, the Variable has the mathematical meaning of that scalar value.

The final situation is a Variable inside a DataGenerator, which may use a target to reference a multi-
dimensional DataSource. In this situation, the Variable has the mathematical meaning of the referenced
external data. If the id of the Variable is used inside a Math element, any function applied to it is
assumed to apply to each individual scalar value of that data.

There are no other situations in SED-ML where the id of a SED-ML element may be used as the
target of a Variable. Also note that multidimensional DataSource ids may not be used in RepeatedTask
elements, nor Range ids in DataGenerator elements. (To access multidimensional data for a Range, a
DataRange may be used instead.)"

---

Then, I added the following to the Range section directly:

"The Range is the iterative element of the repeated simulation experiment. Each Range defines a collection
of values to iterate over. Its id may be used as the target of a Variable within the RepeatedTask by
pre-pending a ‘#’ (i.e. \#rangeId"). It is used in that context to mean the value of the range for the
current iteration of the RepeatedTask."

And adding the following to the DataGenerator section:

"Variable objects in DataGenerator elements may be scalar or multidimensional. If the Math of a Data-
Generator attempts to apply functions to multi-dimensional elements, those functions always apply to
the individual scalar values of that data. If multiple multidimensional Variable ids are used in the same
Math, those ids must each have the same dimensions as each other. No vector or matrix algebra functions
such as dot products or cross products are allowed.

A Variable in a DataGenerator may use the id of a DataSource as its target, pre-pended by a ‘#’, i.e.
\#dataSourceId". This Variable may be multidimensional, and if so, must follow the above strictures."

And finally, in the DataSource section:

"DataSource elements can be used anywhere in the SED-ML Description. Specifically their id attribute
can be referenced as the target of any Variable, pre-pended by a ‘#’ inside DataGenerator, Compute-
Change or SetValue objects if the referenced data is a scalar, and as the target of a Variable in any
DataGenerator even if the referenced data is multidimensional.

The id may also be used as the sourceRef of a DataRange, and as the dataSource or pointWeight of
a FitMapping. These referenced data may be multidimensional."

**Comment by luciansmith** [comment]
@fbergmann : is this correct, in your opinion?

**Comment by fbergmann** [comment]
yes, that reads fine to me. Though i would want one minor modification. While in general indeed the data referenced by a DataSource might multidimensional, in the specific case where it is mentioned (the weight in the fitmapping, there it would be a vector, so one dimensional). Maybe we introduce a paragraph to separate one from the other? Or into parenthesis before the comma?
