### ISSUE TITLE
Discuss the complexity implied by using symbols in ComputeChange and other calculations

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#109]
My interpretation of SED is that simulations are executed in the following order.
1. The model is resolved (e.g., file at URL downloaded, file for BioModels id downloaded)
2. The changes in `model.listOfChanges` are applied to the model.
3. The simulation is initialized.
4. The simulation is executed.

This is based on parts of the specifications that say changes should be applied ***before*** simulation. This allows for modular resolution of models, modification of models, and initialization and execution of simulations. 

Currently, `ComputeChange` calculations can involve values of symbols in simulations. This can be implemented, but requires a different order of execution than that implied by other parts of the specification.
1. The model is resolved (e.g., file at URL downloaded, file for BioModels id downloaded)
2. The simulation is initialized.
3. The changes in `model.listOfChanges` are applied to the model.
4. The simulation is executed.

There's a few issues with this
- This conflicts with the description of model changes in the specifications which states that changes should be applied ***before*** simulation.
- Going by the specifications, it should not be possible to use symbols in compute change calculations because symbols aren't yet defined by the step when changes are applied.
- While this can be done, its more complicated because it breaks the abstraction between model modification and simulation.

A few things could be done to remedy this
- Disallow symbols in `ComputeChange` calculations. 
- The utility of this is limited anyway because `ComputeChange` can only be executed on the initial simulation state.
- Since the value of the one defined symbol is available via the `initialTime` of `UniformTimeCourse`, this can instead be obtained by broadening the use of target (see #106). Since this can be resolved from the SED document itself, this is much easier to implement and can be done with the first order of execution outlined above.

The same issue largely applies to calculations of FunctionalRange and SetValue with a couple differences
- In these cases, there's opportunity to perform calculations based on the end internal state of the simulator from the previous iteration of the repeated task. For iterations beyond the first iteration, this addresses the issue of symbols not being defined at the time when the calculations are executed. 
- This highlights another ill-defined aspect of SED. When FunctionalRange and SetValue calculations are executed, should they be executed using the final state from the previous timepoint, or executed using the simulation for the next task as implicitly specified for ComputeChange? 
  - In the former case, its unclear what the intended behavior is at the first iteration when no previous state is yet available.
  - The later case has similar issues to ComputeChange, that it forces a different order of execution which breaks the modularity between model changes and simulations.

**Comment by matthiaskoenig** [comment]
Symbols would be required to resolve the exact information from the referenced object in target.
E.g. to use `concentration` or `amount` or to use the time symbol.

**Comment by jonrkarr** [comment]
Until this week, symbols were scantly defined. This is turn made computations on symbols largely ill-defined. Now that we have agreed to create more symbol terms and organize them into an ontology, symbols and computations on them are beginning to make sense. I have retitled the issue.

Now that we've agreed to have many more symbols, I think we need to make sure we're all content with the implementational complexity this will introduce. Interpreting the ontology terms for these symbols will be not be optional. This will be essential to interpretation of SED-ML. The ability to exchange SED-ML documents between tools will depend on tools support these symbols. We can allow many symbols to get created, but this could create a lot of work for developers if not managed smartly.

**Comment by luciansmith** [comment]
Updated ComputeChange to now read as follows:

"The change is calculated from the Math of the Calculation, and applied to the target of the Change.
This Math may in turn depend on values calculated from the Model itself, meaning that the interpeters
may need to initialize a model state from the Model before applying a ComputeChange to that state.

Note that when a ComputeChange refers to another model, that model is not allowed to be modified by
ComputeChanges which directly or indirectly refer to this model. In other words, cycles in the definitions
of computed changes are prohibited. This does mean that other models may also need to be initialized
(and changes applied) in order to apply the changes to this model."

Essentially, this formalizes in the spec Jonathan's realization that you have to initialize a model before you can calculate all ComputeChanges.
