### ISSUE TITLE
Update UML diagrams for L1V3 spec

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#11]
There are many issues with the L1V2 UML diagrams which have to be addressed:

- [x] UML diagram for listOfDataDescriptions must be created
- [x] Figure 2.14: The SED-ML listOfModels container: level1/version2 -> level1/version3
- [x] Figure 2.16: The listOfSimulations container: level1/version2 -> level1/version3
- [x] Figure 2.17: The SED-ML listOfTasks container: level1/version2 -> level1/version3
- [x] Figure 2.18: The SED-ML listOfDataGenerators container: level1/version2 -> level1/version3
- [x] Figure 2.19: The SED-ML listOfOutputs container: level1/version2 -> level1/version3
- [x] Figure 2.24: The SED-ML Change class: The class "ChangeAttribute" is spelled "ChangeAtrribute" (reported in [`https://sourceforge.net/p/sed-ml/sed-ml-l1v2/4/`](https://sourceforge.net/p/sed-ml/sed-ml-l1v2/4/))
- [x] Figure A.1: The SED-ML UML class diagram: ChangeAttribute" is spelled "ChangeAtrribute"
- [x] Remove Name attribute from Surface (Figure 2.47: The SED-ML Surface class, Figure 2.42: The SED-ML Output class, Figure 2.44: The SED-ML Plot3D class: Technically the 'name' attributes doubles in Surface in the UML, because it's already inherit from Curve.
- [x] AlgorithmParameter missing in Figure 2.32: The UniformTimeCourse class
- [x] ListOfParameters and ListOfVariables missing on the DataGenerator  Figure
- [x] In the full SED-ML UML diagram, an arrow is missing to say that the SetValue class inherit from ComputeChange.
- [x] The UML for the 'SetValue' class (in Figure 2.34) is missing many things. It is missing the fact that it inherits from the computeChange class, and well as not mentioning its new mandatory modelReference attribute, nor the two optional attributes range and symbol.
- [x] The UML for the 'Task' class (figure 2.33) uses weird-to-me iconography to indicate that an attribute is a string reference to an element. Is this actually standard UML? Being familiar with the SBML UML diagrams, this would there be indicated by listing the attribute names inside the box, with an attribute type of 'string' or 'SedIDRef' or 'ModelRef' or something. Before I noticed that there was no black diamond on the line, I assumed that you were actually talking about child elements! (reported in https://sourceforge.net/p/sed-ml/sed-ml-l1v2/9/)
- [x] For what it's worth, the 'SubTask' class has a 'task' attribute that's of type 'SIdRef'--I think it'd be best to make this iconography consistent, at least. (reported in https://sourceforge.net/p/sed-ml/sed-ml-l1v2/9/)
- [x] On page 52 and also in the overview, the UML diagram states a 'index' attribute, which is not mentioned in the text nor the example (this should be range) (reported in https://sourceforge.net/p/sed-ml/sed-ml-l1v2/13/)
- [x] DataDescription class lists: listOfDimensionDescriptions, which is only dimensionDescription

Personally, I am still strongly for recreating the UML diagrams for L1V3. The latest for L1V4 we have to do the work. So would be better to invest some time now than fixing the old things.

M

**Comment by luciansmith** [comment]
I'm still largely of the opinion that any time spent on the l1v3 spec is time that delays l1v4.  That said, many of the new figures I've created could be used as-is in l1v3 if you wanted to drop them in--the new figure for Frank's data class in particular would work, and that figure is a completely different style anyway.

That said, I'm certainly not going to *stop* anyone from making l1v3 figures that are more accurate than the current set.  It should be relatively straightforward to take the figures I made for l1v4 and tweak them for l1v3.  The main thing to remember is that we put 'id' and 'name' on SedBase for l1v4, and it's not there in l1v3, so you'll need to put them back for anything that had them.

**Comment by fbergmann** [comment]
Reading this I'm still a proponent of just releasing l1v3 as soon as many
Matthias implements the data stuff. After that you are free to up open
things up with the next level as proposed by the current editors and
Herbert.

**Comment by matthiaskoenig** [comment]
No problem. I will update the figures and fix the obvious issues in the current L1V3 draft (I don't feel comfortable with all this obvious errors in the spec which can be fixed in a timely manner). 
@luciansmith perhaps we could have a quick hangout and you show me 15 min how you create the figures in google draw

I should be finished with implementation and specification update end of next week. So we should get out the spec in July (i.e. latest 2017/07/30).
