### ISSUE TITLE
Replace symbol URNs with KiSAO terms

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#111]
Symbol URNs are similar to an ontology in that they define a shared list of terms. However, the current implementation is just a list of strings. In contrast, an ontology (e.g., OWL file) can capture a variety of information about each term such as a description, citations, relationships to other terms, etc. Using an ontology also provides the ability to use BioPortal, OLS, and other sites to search and browse the available terms. 

Given the existing connection with KiSAO, the obvious ontology to move this information to is KiSAO. Specifically, a new section of KiSAO could be added for symbols. By moving symbols out of the SED specifications, this would also enable symbols to be added more quickly.

**Comment by matthiaskoenig** [comment]
related to #123 and #124

**Comment by luciansmith** [comment]
One question on this:  do we want the name of the attributes in question or the types to change?  For example, do we change:

  term:  URN

to something like:

  term: kisaoID

or:

  kisaoTerm: kisaoID

?

Or do we just recommend(/require?) using KiSAO terms *as* the URNs?

**Comment by jonrkarr** [comment]
I think the key thing is to change the data type of the attribute. I don't have a strong opinion about the name of the attribute. It could stay the same. For symmetry with algorithms and algorithm parameters, how about renaming the attribute to `symbolKisaoID`?

The old syntax
```
<variable task="task1" symbol="urn:sedml:symbol:time"/>
```

could become this:
```
<variable task="task1" symbolKisaoID="KISAO_XXXXXXX"/>
```

**Comment by fbergmann** [comment]
We have `symbol`, `symbol2` and `term` if we consider variables & dependent variables. I am not sure that we do need to rename the attributes, instead we just specify that their values would either be coming from the `sedml:symbol` (deprecated starting with L1V4) or kisao terms. 

Btw, it would be `KISAO:....` rather than `KISAO_...`, right?

**Comment by jonrkarr** [comment]
Sorry for the confusion, yes we've agreed on `KISAO:...` (`:` rather than `_`).

**Comment by luciansmith** [comment]
This change is now incorporated!  There were numerous small fixes here and there in https://github.com/SED-ML/sed-ml/commit/8361aa5e84912410db0eeee5310cfe462a540f9a ; the main change is:

"The symbol attribute of type string is used to refer either to a predefined, implicit variable or to a predefined implicit function to be performed on the target. In both cases, the symbol should be a kisaoID (and
follow the format of that attribute) that represents that variable’s concept. The notion of implicit variables is explained in Section 3.2.5. For backwards compatibility, the old string "urn:sedml:symbol:time"
is also allowed, though interpreters should interpret "KISAO:0000832" as meaning the same thing."

Any wording change suggestions welcome.
