### ISSUE TITLE
When sub-tasks involve different models, optionally use an additional dimension to encode their results

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#113]
The specifications say that the results of sub-tasks should be concatenated together end-to-end. This makes sense in some cases. For example, this make sense if the sub-tasks represent short time steps of a time course. When the sub-tasks involve different models, this data structure can be cumbersome to work with. In that case, I think sub-tasks should be encoded into a separate dimension so that the results of individual subtasks can easily be selected out.

This could either be done automatically on the basis of whether all of the subtasks use the same model, of an attribute could be added to allow the investigator to control the organization of the report that's produced.

**Comment by luciansmith** [comment]
A 'concatenate' attribute was added to RepeatedTask to address this issue, cf https://github.com/SED-ML/sed-ml/issues/150
