### ISSUE TITLE
Second implementation of L1V3 data

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#12]
Still have to finish the second implementation in tellurium 
Current status:
* data is read from numl

Still Missing
- [x] read data from csv
- [x] use data in DataGenerators and plots
- [x] csv and numl example
- [x] indexSet and slice example

Just posting this here you have update when this is finished.

**Comment by fbergmann** [comment]
Great news indeed, also when i came back I've updated the python bindings so you also will get more debugging hints in pycharms ...

**Comment by matthiaskoenig** [comment]
Thanks for that. This will help a lot.

**Comment by matthiaskoenig** [comment]
Good news everyone. Second data implementation is finished.
