### ISSUE TITLE
Change 'term' of DependentVariable to reference KiSAO

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#123]

**Comment by luciansmith** [comment]
https://docs.google.com/spreadsheets/d/1f3rBUUhOsB6k7-i_ins0nlB7PTtd_huvhgFrCOh501U/edit#gid=0

has my list, which is currently bereft of KiSAO terms.

**Comment by fbergmann** [comment]
that list is great. Though i was hoping for rateOfChange to be `sybmol` rather than `term`. As what the simulators will likely do is to `just` return the internal rate of change they have available for the element. I don't think that arbitrary differentiation would be implemented. But i guess that will be a minor point.

**Comment by luciansmith** [comment]
I was thinking about CellML when adding rateOfChange there, because I *think* they're more likely to have, if not arbitrary differentiation, at least differentiation for the main variable of the simulation, which might not be 'time'.

I put it as a 'term' because if you need to say 'the rate of change of the amount of S1', you need the symbol to say 'amount'.  (For that matter, if you need 'the rate of change of the amount of S1 with respect to the amount of S2', you'll need all five attributes!)

**Comment by fbergmann** [comment]
And i can understand why you did that, though i would not expect any CellML tool to provide any rate of change of one component with respect to anything but time. But i'm fine with keeping it that way. 

in COPASI we also use particle number rate for species, and for reactions we have flux and particle number flux. Not sure we need them here.

**Comment by luciansmith** [comment]
I'd be happy to add them!  I think the current suite can work for particle number rate for species:

    target = species ID, symbol = 'particle number' term = 'rateOfChange', symbol2 = time

Would it be sufficient to have, for particle number flux:

    target = reaction ID, symbol = 'particle number'

Would it make sense to use 'amount' for non-particle-number-flux, i.e.

    target = reaction ID, symbol = 'amount'

or do we need something new like 'extent'?

    target = reaction ID, symbol = 'extent'

**Comment by fbergmann** [comment]
Thanks! As for `extent`, i'm afraid we could not support that, as we dont support arbitrary reaction extents. We either display them in terms of concentrations or particle numbers in the user interface.

**Comment by luciansmith** [comment]
We certainly don't need to add anything that nobody can use ;-)

If we already have 'amount', 'concentration', and 'particle number', it sounds to me like we don't need to add anything else at the moment.  Unless I misunderstood something?

**Comment by fbergmann** [comment]
i think we are good, thanks

**Comment by luciansmith** [comment]
Fixed with https://github.com/SED-ML/sed-ml/commit/8361aa5e84912410db0eeee5310cfe462a540f9a
