### ISSUE TITLE
Add `amount` and `concentration` as symbols

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#124]
To be able to set initial concentrations or initial amounts via SED-ML and to access the respective quantities in the data generators the additional symbols `amount` and `concentration` must be added. 
This works then in combination with the xpath selecting the object (species).

**Comment by fbergmann** [comment]
lets also add `particlenumber`.

**Comment by nickerso** [comment]
Is this specifically for SBML models (i.e., species) or should these concepts be applicable across modelling formats?

**Comment by luciansmith** [comment]
@nickerso : I believe this should indeed be applicable across modeling formats, but I'm not sure if it's quite as immediately useful to CellML (certainly it would work for BNGL, whose underlying object model is the same as SBML's).

This is what I have in the spec at the moment:

"symbol
The optional symbol attribute of data type URN may be used in addition to the target when the particular value associated with the target may be described in multiple ways. In particular, a species
whose value could be expressed either as a concentration or an amount may have its concentration
set by using the symbol "urn:sedml:symbol:concentration", or its amount set by using the symbol
"urn:sedml:symbol:amount"."

If we want to change these to KiSAO terms, that's fine with me; I'm happy to change the text once the terms exist.

(Also, I could add 'particleNumber' as an example in the spec or not, depending.  It absolutely should be legal, but I don't know if it needs to be called out in the spec or if that would just be confusing.)

**Comment by luciansmith** [comment]
With https://github.com/SED-ML/sed-ml/commit/8361aa5e84912410db0eeee5310cfe462a540f9a I changed the above text to reference the new KiSAO terms instead of the sedml URNs.  Other than that, everything is updated.
