### ISSUE TITLE
Remove SimpleRepeatedTask

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#129]
I see the urgent need to update the RepeatedTask for L1V4. This is the most complex and misunderstood part of SED-ML and at the same time the core of it. 

Here my suggestions summarizing other issues
- Simplify SetValue by removing ComputeChange. This can be handled cleaner in the FunctionalRange and removes large block of duplicate functinality  (#101)
- Move list of changes to subtasks (improved funationality, more use cases, more consistent) (#128)
- Make ids required on Subtask for simpler handling of results (see #107)
- Clarify meaning of resetModel (#110)
- Clarify concatenation of subtasks (sometimes these should form one concatenated output, other times not, perhaps add a new flag). There is large confusion around this. See also #113
- Remove the SimpleRepeatedTask! By simplifying the repeatedTask we do not require a SimpleRepeatedTask.
- add clarifications about multiple models (see #105)
- require subtask order to be unique (see #95)

This will make working with the data much easier because things are more consistent and clear from the data side. This would allow us to handle things like #103 and make the generation of the 3D plots easier.

**Comment by luciansmith** [comment]
Given that all of your suggestions are repeated here from elsewhere except one, I'm going to change this particular issue to be just that single issue:  remove SimpleRepeatedTask.

If nobody implements support for SimpleRepeatedTask, we'll end up following this suggestion by default.

**Comment by luciansmith** [comment]
Done!  (But easy to reverse if need be.)
