### ISSUE TITLE
Clearer formulation for axis label required

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#132]
The specification currently reads for `name` on axis:

>The Axis class inherits the name attribute from SEDBase, but it is worth noting that it is commonly used as a label for the axis.

This should be formulated more strict as.

>The Axis class inherits the name attribute from SEDBase. If the `name` is set on an Axis it must be used as the label of the axis.

**Comment by luciansmith** [comment]
Would you be OK with 'should' instead of 'must'?  If nothing else, it would be an unenforceable rule, as there is no way to validate a plot.

**Comment by matthiaskoenig** [comment]
With the `must` I refer to: In the case your tool shows axis labels on a plot these must be the name of the axis with a fallback to id. Should reads like one can choose what to show in the axis labels. This is just a wording issue, but I don't want to say that you have to show axis labels to have a valid implementation.

**Comment by luciansmith** [comment]
Changed the 'name' section to 'name and id' and changed the text to:

The \Axis class inherits the \element{name} and \element{id} attributes from \SedBase.  The \element{name}, if present, should be used as the label for the axis.  If it is not present, the \element{id} may be used.
