### ISSUE TITLE
Additional curve types `barGrouped` and `horizontalBarGrouped`

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#138]
We only have bar and barStacked curve types in the specifiction. In addition there is the option to group bars, i.e. plot bars for the different groups next to each other.
Currently the bar type is underspecified and it is up to the implementation what to do if multiple bar curves are plotted at once. I suggest to add `barGrouped` and `horizontalBarGrouped` to clarify the difference and allow to code for both types of bar graphs.

See attached an example how the current types would look (without and with symmetrical errorbars):
![curve_types_figure0](https://user-images.githubusercontent.com/900538/113359244-ada27b80-9347-11eb-907f-d60e2d6b8dba.png)
![curve_types_errors_figure0](https://user-images.githubusercontent.com/900538/113359270-ba26d400-9347-11eb-95a6-8cf0a1f0fcdc.png)

The `barGrouped` would look like the following
![image](https://user-images.githubusercontent.com/900538/113359161-7f24a080-9347-11eb-9662-0091a8b79a27.png)

**Comment by luciansmith** [comment]
I think it's clear that if you can group the bars, you should group the bars.  Plotting bars on top of each other is silly, notwithstanding the fact that matplotlib can only do that.

**Comment by matthiaskoenig** [comment]
This is a common use case and I see this a lot. Classical thing are two overlapping histograms which you do not want to group but see the overlap to clearly see the difference in the distributions.
This is a layered/overlapping histogram as defined in:
https://altair-viz.github.io/gallery/layered_histogram.html
With many examples existing for this kind of plot
https://www.google.com/search?q=images+overlaying+histogram&source=lnms&tbm=isch&sa=X&ved=2ahUKEwito8ehpt_vAhWDg_0HHer2BnoQ_AUoAXoECAEQAw&biw=1242&bih=875&dpr=2

I am using such plots with distrib. Please see attached a figure from one of my manuscripts in preparation. Here a protein is sampled for different subpopulations and the stratified model is simulated. To visualize the shift in CYP1A2 protein amount I am using a overlapping histogram.
![image](https://user-images.githubusercontent.com/900538/113406135-44545400-93ab-11eb-8c50-800630d8cb8f.png)
The model is simulated from this distribution.

I always understood the `bar` as a bar plot which would overlap with multiple curves. I only noticed that we understand different thing when I saw your implementation compared to mine ;).

**Comment by luciansmith** [comment]
Well, OK, I guess I stand corrected.  If someone wants to implement support for this by the deadline, I'd not be opposed to the idea.

However, my sense is that people want to pull SED-ML *away* from overdefining figures, so adding new options at this stage of the game seems a little fraught.  Again, I wouldn't actively oppose the idea, but I'm not going to be pouring a lot of resources into it, either.  (Also, it seems like our implementations should indeed do the same thing, since matplotlib doesn't do grouped bar plots in the first place?  I thought this was a problem, but maybe it isn't.)

**Comment by matthiaskoenig** [comment]
There are two solutions for me:
- 1. We add the types and I would provide implementation for the `groupedBar`.
- 2. We don't add the grouped versions and make sure that the `bar` is described as overlay bar, not as a grouped bar in the specification (I mainly need overlayed bars, so I am fine with this).

**Comment by matthiaskoenig** [comment]
I just checked the specification and the bar is clearly described as an overlayed bars plot. No need for the groupedBar. Closing this issue.
