### ISSUE TITLE
L1v3 specs:  'id' and 'name'.

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#139]
This is actually a question about L1v3, and how to interpret it.

Before we put 'id' and 'name' on SBase, we explicitly put them on individual classes that we thought needed them.  In the UML diagrams, there were some classes that got both, some that got just 'name' but not 'id', and some that got 'id' but not 'name'.

However, in the "Attributes and nested elements for XXX" tables, all of them list both 'id' and 'name'.  The text descriptions never mention both if both weren't in the UML.

Here's the full breakdown:

* Range:  only 'id' in the UML; no table with allowed attributes (for either Range or the various classes that inherit from Range), so nothing ever mentions 'name' being allowed.
* Curve:  only 'name' in the UML; both 'id' and 'name' in Table 2.28
* DataSet:  only 'name' in the UML; both 'id' and 'name' in Table 2.30
* Surface:  only 'name' in the UML; both 'id' and 'name' in Table 2.29  (Also, inherits from Curve.)

I'm not particularly adept at reading schemas, but I *think* all four classes seem to be in the 'idgroup', which defines both 'id' and 'name'.  So there's that, too.

The issue comes up because Frank and I are trying to get libsedml to interpret all levels and versions of SED-ML correctly.  The same issue would arise for jlibsedml or any other SED-ML interpreter.

Overall, my inclination is to allow both id and name for all four classes.  Other options include:

* Only allow 'id' for Range, allow both for the other three.
* Follow the UML and only allow 'id' for Range, and only allow 'name' for Curve/DataSet/Surface.

Opinions?

**Comment by fbergmann** [comment]
looking through the SED-ML specifications, it is clear that `id` was meant to be on curves / surface as it is mentioned also on the schema, in the examples and the table.  (note that the dataset does not have an id in the schema, but in the example and table it does). 

This goes back to the early specs too, so i would not disallow `id` on them.

**Comment by luciansmith** [comment]
What's your opinion on 'Range'?  id/name, or just id?  UML has just id; schema has id/name, no examples/tables that I could find either way.

**Comment by fbergmann** [comment]
i have no preference on name. But libSEDML never had support for names in ranges. Neither did jlibsedml. So if we add it to an l1v3 errata those will have to be changed.

**Comment by luciansmith** [comment]
Let's leave it off, then!

**Comment by luciansmith** [comment]
The upshot, if anyone comes back to this:

* Range gets 'id' but not 'name'.
* Everything else in L1v3 with an id or name in the UML gets *both* 'id' and 'name', including DataSet, Curve, and Surface.

Again, in l1v4, 'id' and 'name' are added to SBase, making any distinctions moot.  this is for l1v1->l1v3 only.
