### ISSUE TITLE
Validation rules in specification

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#14]
[`https://sourceforge.net/p/sed-ml/sed-ml-l1v2/19/`](https://sourceforge.net/p/sed-ml/sed-ml-l1v2/19/)

Can we have validation rules for SED-ML in the specification?

**Comment by jonrkarr** [comment]
Do you mean validation such as uniqueness? Yes, I agree this would be helpful. E.g., tuples of (Task.id, `SubTask.order`) should be unique.

**Comment by luciansmith** [comment]
DEVISER can auto-generate many of these, but the rest are going to have to be created manually.

@fbergmann : what do we have to do to get validation rules out of Deviser, and is there a SED-ML L1v4 Deviser input file?

**Comment by jonrkarr** [comment]
I think it would be very helpful to have deeper validation that, for example, checks XPATHs for XML encoded models.

**Comment by luciansmith** [comment]
First pass at this (from Deviser):  https://github.com/SED-ML/sed-ml/commit/7b530ecf85aac217f88f7233aa997ce3a9551e2b

**Comment by luciansmith** [comment]
Given https://github.com/SED-ML/sed-ml/issues/182, I'm closing this issue, as the first pass at validation rules are now done.
