### ISSUE TITLE
What are the rules for interpreting aggregate mathematical functions (min, max, sum, product)?

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#152]
At first glance, the semantics of these functions seem unclear because it requires symbols do have different meaning depending on their context. Example:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <apply>
    <divide/>
    <ci> task1_____PX </ci>
    <apply>
      <csymbol definitionURL="http://sed-ml.org/#max" encoding="text">max</csymbol>
      <ci> task1_____PX </ci>
    </apply>
  </apply>
</math>
```

Questions
- Are symbols always interpreted to be vectors inside these aggregate functions?
- Can these aggregate functions be used to calculate the min or max of two different symbols? If so, how is one intended to communicate this should be a scalar rather than a vector calculation? If the symbols are vectors, is this intended to be an element-wide computation or operate over the entire vectors?
- How are these functions intended to be executed for results of repeated tasks which are multidimensional? or results of spatial simulations which could be multi-dimensional?
- Why are these defined with `http://sed-ml.org/#max` rather than MathML? The specifications suggest these are MathML functions, but this suggests otherwise. This isn't ideal because the SED-ML specifications don't clearly define the semantics of these functions.

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <apply>
      <csymbol definitionURL="http://sed-ml.org/#max" encoding="text">max</csymbol>
      <ci> task1_____PX </ci>
      <ci> task1_____PY </ci>
    </apply>
</math>
```

**Comment by luciansmith** [comment]
Fixed with https://github.com/SED-ML/sed-ml/commit/c1b1e9bb10043c0de8ffc20473c4ae289b9e9b3a
