### ISSUE TITLE
Clarify the semantics of the aggregate mathematical functions

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#153]
As described in #152, the semantics of the aggregate mathematical functions is unclear. Can some of these except multiple arguments (e.g., two calculate the min of two variables)? This should be clarified.

**Comment by luciansmith** [comment]
Fixed with https://github.com/SED-ML/sed-ml/commit/c1b1e9bb10043c0de8ffc20473c4ae289b9e9b3a
