### ISSUE TITLE
Clarify introductory description of "aggregate" mathematical functions

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#154]
Section 3.1.3 of the specifications introduces all of the special math functions as "aggregate" functions (e.g., that operate on vectors). As far as I can tell, the probably distribution functions are intended to have scalar arguments. If this is the case, this should be clarified.
- `uniform`
- `normal`
- `lognormal`
- `gamma`
- `poisson`

**Comment by luciansmith** [comment]
Fixed with https://github.com/SED-ML/sed-ml/commit/c1b1e9bb10043c0de8ffc20473c4ae289b9e9b3a
