### ISSUE TITLE
Remove unsupported math elements from specifications: lambda and bvar, maybe min/max?

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#156]
How are function definitions intended to work. Can someone please provide an example?

**Comment by fbergmann** [comment]
I dont think there is explicit support for functiondefinitions in SED-ML. I dont see where it could be called from. I see them only used in SBML. Do you need an example there?

**Comment by jonrkarr** [comment]
I ask because they're described in the specifications. 

If these are intended to be supported, they should be removed from the specifications. I'll edit the title accordingly.

**Comment by luciansmith** [comment]
If we deal with min/max/etc entirely with the 'term' attribute on DependentVariable, we should take them out of the MathML, too.  I'm 98% sure that nobody implemented support for them.

(For that matter, we also need implementation of the other 'draw from a distribution' functions, or we should drop them, too.)

**Comment by luciansmith** [comment]
lambda and bvar now removed; leaving this here in case we want to remove more things.

**Comment by jonrkarr** [comment]
I'm in favor of removing the aggregate methods. I think the current scheme -- with the meaning of variables depending on their context -- is complicated.

**Comment by luciansmith** [comment]
Removed the remaining dimension-reducing functions, but I think we should probably vote on this.  The main problem with this I can imagine would be if there was already implementation for the older l1v3 functions we already defined.

Jonathan has voted in favor, meaning we need to hear from a majority of @matthiaskoenig , @fbergmann , @nickerso , and Tomas (whose github id I don't seem to have?).

**Comment by jonrkarr** [comment]
Lucian proposes to describe such functionality via KiSAO ids for specific observables.

Seeing as it sounds like simulation tools don't support these MathML functions, it sounds like removing this would have no practical effect, except that an example that tools can't execute needs to be deleted. I think removing examples that tools can't execute is good; this removes a source of confusion and frustration.

**Comment by matthiaskoenig** [comment]
There are multiple implementations for min/max. For two examples see the SED-ML L1V3 specification in Figure 1.5/1.6. Both tellurium and SED-ML Webtools implement the min/max support as do I in sbmlsim.

**Comment by luciansmith** [comment]
I've updated the repressilator example to use the new DependentVariable way of doing things.

Do we want to leave max/min, given that we have implementations, then?  Or do we ditch them for l1v4 since it's not actually very well defined?

**Comment by luciansmith** [comment]
To sum up:  min, max, sum, and product were all present in l1v3.  They all returned scalar values, and had to explicitly state that these functions alone took a single argument of type Variable, and that the Variable in question represented the full dimensionality of the referenced Task.

We now have a more robust way of calculating all four of these functions (and more) with the DependentVariable construct, which can themselves return scalars or vectors in arbitrary dimensions.  Strictly speaking, then, we no longer need the old versions, but it might be nice to maintain backwards compatibility, since at least min and max did get support from some SED-ML interpreters (not sure about sum/product).

**Comment by matthiaskoenig** [comment]
I also supported `sum` and `product`. I am strongly in favor for deprecating the old `min/max/sum/product` in L1V4. I.e. let's have only a single clear way to do things which works ;).

**Comment by luciansmith** [comment]
Leave them in for backwards compatibility, but point to new way.

**Comment by luciansmith** [comment]
New intro paragraph for old functions:

"While the new DependentVariable class provides functionality to reduce the dimensionality of matrices,
previous version of SED-ML defined the MathML functions min, max, sum, and product, each of which
would reduce any n-dimensional vector to a single scalar value. It is recommended that users switch to
using DependentVariable elements for their increased functionality, but the old functions are still defined
here for backwards compatibility. The only allowed symbols to be used in aggregate functions are the
identifiers of Variables defined in the listOfVariables of a DataGenerator. These Variables represent
the data collected from the simulation experiment in the associated Task. They always return scalar
values, regardless of the dimensionality of the Variable, and ignore any NaN values the vector or matrix
might have."

**Comment by fbergmann** [comment]
that formulation is fine with me

**Comment by matthiaskoenig** [comment]
fine with me
