### ISSUE TITLE
Allow free text at the end of KiSAO IDs.

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#164]
One thing I'm noticing is that as I switch to KiSAO terms, any information about what they actually are disappears.  For Algorithm Parameters, this can be solved by using the 'name', but for the 'term', there's no good place to put it.

What if we stole a page from URLs, where newspapers or other organizations put the title of the article as part of the URL string that then gets ignored by actual URL interpreters?  I'm imagining something like:

        <dependentVariable id="S2_avg" term="KISAO:0000825?n=average" 
                       target="/sbml:sbml/sbml:model/sbml:listOfSpecies/sbml:species[@id=&apos;S2&apos;]" 
                       taskReference="task1" modelReference="model0">

**Comment by matthiaskoenig** [comment]
This is a general problem I have with annotations. Things just become unreadable and less comprehensible. I never understood why not just use a better id pattern for ontologies such as
KISAO:AVERAGE
KISAO:MEAN
instead of putting numbers in the id.

I would support such a solution, but libsedml should have some helpers to easily work with this such as
```
dependent_variable.getTerm()
dependent_variable.getTermKiSAO()
```
which gives either the complete term or only the kisao part.

**Comment by luciansmith** [comment]
I totally agree about libsedml: I already have plans to have 'setKisaoId(43)' not only set the kisao ID to the right string, but also set the 'name' for an algorithm parameter (if the name isn't already set).  I would also like to have 'getKisaoName(43)' give you the name of KISAO:0000043.

But since that won't work for the 'term', I wanted to come up with a different option, and thought I'd throw this out there.  Other schemes would also be fine, of course.

**Comment by nickerso** [comment]
I don't think we should do this. Ontology IDs are well defined and mangling them with such additional text seems like a very bad idea. Adding convenience methods to the libraries and/or UI in GUI tools to present more information than just the ontology ID is definitely the way to go.

**Comment by luciansmith** [comment]
Hmm--what if we added a 'termName' optional free text attribute instead, for the same purpose?

**Comment by nickerso** [comment]
as a SED-ML attribute? I don't object to that, but can see it easily becoming confusing as people may use that to imply meaning. And how tools interpret it when the KiSAO ID is out of sync. Improved methods to look up KiSAO terms and present them to users in a meaningful manner is more robust...but obviously doesn't help for those looking at the raw SED-ML as XML text.

**Comment by fbergmann** [comment]
yeah, i'd be against adding termname, we have the id, if people wanted to provide more information they could always add notes and annotations. I wouldnt want the id and name to diverge as they might when the ontologies develop further.

**Comment by luciansmith** [comment]
I think we're good to close this--it's not super necessary, for all that it would be nice, and can be accounted for in the normal 'name' for the element.
