### ISSUE TITLE
Clarify which model variables are used in FunctionalRange and SetValue

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#167]
Hi all,
there are some confusing formulations in the spec in respect to FunctionalRange and Set Value:

**2.2.9.3.4 "FunctionalRange":** 
>The value of any Variable child of a FunctionalRange should be calculated before the first simulation begins, and will not be affected by any SubTask in the RepeatedTask.

**2.2.9.2: "SetValue":**
> Again as for functionalRange, variable references retrieve always the current value of the model variable or range at the current iteration of the enclosing repeatedTask.

**The issues are:**
- 2.2.9.2 is contradicting 2.2.9.3.4, i.e. the FunctionalRange uses the initial values not the current values (so that all ranges can be calculated before the iterations)
- information in 2.2.9.3.4 is underspecified: i.e. should the initial variables be used before or after the list of changes is applied to the model

I suggest the following fixes:

**2.2.9.3.4 "FunctionalRange"**
>The value of any Variable child of a FunctionalRange should be calculated after the listOfChanges are applied to the models and before the first simulation begins, and will not be affected by any SubTask in the RepeatedTask.

**2.2.9.2: "SetValue":** 
>In contrast to functionalRange, variable references in setValue retrieve always the current value of the model variable and the range at the current iteration of the enclosing repeatedTask.

Best Matthias

**Comment by luciansmith** [comment]
I agree!  Good catch.  The SetValue text was written when I had a different idea of what FunctionalRange should mean.

**Comment by luciansmith** [comment]
(Also:  I've been reserving the 'draft fix' label for after text is actually changed in github.  If you're up for making the change, that'd be great.)

**Comment by matthiaskoenig** [comment]
Yes, will include the change now.

**Comment by matthiaskoenig** [comment]
I had to change the second part to before ListOfChanges; Otherwise there could be strange circular behavior. I.e. the listOfChanges could depend on ranges (so it is something range dependent which is changed in iterations).
If one wanted to change values before one could always create a new model with changes or add the change to the actual functional range.

**2.2.9.3.4 "FunctionalRange"**

> The value of any Variable child of a FunctionalRange should be calculated **before** the listOfChanges are applied to the models and before the first simulation begins, and will not be affected by any SubTask in the RepeatedTask.
