### ISSUE TITLE
Incorrect kisao ids for seed and absolute tolerance in specification

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#173]
The kisao ids have been switched for seed and absolute tolerance in the specification and are incorrect at many places.
`KISAO:0000211 : absolute tolerance`
`KISAO:0000488 : seed`

E.g.
> NOTE: the global ListOfAlgorithmParameters was added to SED-ML in Level 1 Version 4. As such,
the only place to define a random seed (KISAO:0000211)

or in section 2.2.1.11 and listing 2.24
```
<listOfAlgorithmParameters>
2 <algorithmParameter name="seed" kisaoID="KISAO:0000211" value="23"/>
3 <algorithmParameter name="absolute tolerance" kisaoID="KISAO:0000488" value="1001"/>
4 </listOfAlgorithmParameters>
```

Solution: Check the kisao ids are correct and set `name` on all AlgorithmParameter examples in the spec.

**Comment by luciansmith** [comment]
Done!
