### ISSUE TITLE
Add hyperlinks from specs to online examples

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#177]
Such as `L1V3_repressilator.omex`: https://github.com/SED-ML/sed-ml.github.io/raw/master/examples/L1V3/L1V3_repressilator.omex

**Comment by luciansmith** [comment]
Done!  I put in links to the SED-ML files directly, but the links are really large.  Can we add just the SED-ML itself (as opposed to the version that's hidden inside an OMEX file) to sed-ml.org?

**Comment by jonrkarr** [comment]
We could unpack those example archives and add links to the individual files.
