### ISSUE TITLE
Make id attributes optional

### ISSUE THREAD

**Issue by jonc125** [SED-ML/sed-ml#18]
Recreating from Sourceforge because I have a strong wish for this :)

Original description:

> Requiring id attributes for things like curve, surface, dataSet (see Tables 2.28-2.30 in the L1V2 draft) is incredibly irritating, leading to id proliferation, and it seems to me rather pointless. Sample documents often omit them. Could we make them optional? Generally, I think an id should only be required for things that definitely need to be referenced from other parts of SED-ML documents.

> (Related to this is the larger issue of ids needing to be globally unique across a SED-ML document, of course.)

Matthias said:

> Personally I prefer every object having ids. This makes many things in implementations much easier like
> - hashing things for fast access being the number one for me
> - also one can create graphs with all nodes being uniquely identified
> - also automatic code generation from SED-ML in programming languages becomes much easier because once can just id the respective instances via the unique ids

To which I point out:
* The `id` attribute would still be *permitted* everywhere, just not required
* Tools can therefore easily add an auto-generated unique id to any element if they wish
* It's a pain if you're creating or editing files by hand to have to generate unique ids yourself for things you don't need to reference
* Things may be better now, but most of the SED-ML documents I saw when I originally created the issue didn't include many of these ids...

**Comment by matthiaskoenig** [comment]
I could life with ids being optional but only under the condition of
* every object must have an id attribute (i.e. either optional or required)
* ids must be globally unique (or there must be another optional global unique field like metaId in SBML).

**Comment by jonc125** [comment]
Yes, that is what I meant!

**Comment by luciansmith** [comment]
Everyone seemed OK with putting an optional 'id' and 'name' on SedBase for l1v4.  It sounds like this is a further proposal to downgrade some of the ids to 'optional' from 'required'.  Am I right?  I would also be OK with this.  The classes that should have required IDs are the classes that define things that it only makes sense to create in the first place if they are going to be referenced somewhere else.

It sounds like Curve, Surface, and DataSet are not often (if ever?) referenced elsewhere in the SED-ML file.  Are there other classes that are similarly reasonably useable without an ID?

**Comment by jonc125** [comment]
Yes, that's the idea.

Afraid it's been a while since I looked at the spec, so not sure if there are other candidates for downgrading.

**Comment by matthiaskoenig** [comment]
Sounds great. Seems like we are all on the same page. 
I put this on the list for the L1V4 enhancements. 

We are currently working on getting L1V3 out. L1V3 would than form the baseline for the changes/enhancements/features for L1V4. So we should go over all the ids (and change some from required -> optional) as soon as L1V3 is out.

The current spec states:

> Most objects in SED-ML carry an \concept{id} attribute. The \hyperref[sec:id]{id} attribute, if it exists for an object, is always required and identifies SED-ML constituents unambiguously.

We have to go over the individual classes and decide on which to make ids optional and change the statement to something like

> Most objects in SED-ML carry an \concept{id} attribute. The \hyperref[sec:id]{id} attribute, if it exists for an object, is required (if not stated otherwise in the class definition) and identifies SED-ML constituents unambiguously.

**Comment by matthiaskoenig** [comment]
This is part of the spec and decided. Closing this here.
