### ISSUE TITLE
Provide additional advice for users to the introduction of the specifications

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#183]
Because the specifications serve as the main documentation (including for users) of SED-ML, I think it would be helpful to add some additional useful information to the introduction about SED-ML can be used.

- Pointers to where to find published SED-ML files (https://www.ebi.ac.uk/biomodels/, JWS)
- Pointers to information and examples of using SED-ML with specific model languages, simulation algorithms, algorithm parameters, XPaths for observables, etc. (https://biosimulators.org)
- Pointers to where users can find software tools that support SED-ML (http://sed-ml.io)
- Pointer to where users can find a tool for validating a SED-ML document (https://run.biosimulations.org)

**Comment by matthiaskoenig** [comment]
I agree. But we should manage all the actual links on the homepage to be
able to do updates.

**Comment by luciansmith** [comment]
Added this to the front page:

To find the most up to date information about SED-ML, including links to
published SED-ML files, examples, and supporting software, please visit
http://sed-ml.org/

**Comment by matthiaskoenig** [comment]
This reads great.
