### ISSUE TITLE
Model language URN table should encompass additional newly supported languges

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#184]
- LEMS: `urn:sedml:language:lems`
- Smoldyn: `urn:sedml:language:smoldyn`
- ZGINML (GINsim): `urn:sedml:language:zginml`

All have implementations

**Comment by luciansmith** [comment]
Done!  Also added the other missing URNs from the sed-ml.org/urns.html web page.

**Comment by jonrkarr** [comment]
Thanks. I had held off on the others because there's no SED-ML implementations yet. I think its good to include them. This helps suggest that SED-ML is welcoming of more languages.

**Comment by luciansmith** [comment]
Can we add a new column on the web site (not in the spec) that mentions known implementations?

**Comment by jonrkarr** [comment]
BioSimulators has that information. We could add a link to that. I'd prefer not to maintain similar information in two places, plus "support" is a nuanced concept that's hard to capture with just an additional column.
