### ISSUE TITLE
Add attribute `reduction` for reduction function on variable (AppliedDimensions)

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#188]
Currently, the AppliedDimension uses the `term` attribute from the `DependentVariable` to define the reduction function. This is confusing in some ways:
- the term is used in multiple contexts, i.e. either for a DependentVariable or the DimensionReduction
- The listOfAppliedDimensions is linked in the UML to the Variable, but should be linked to the DependentVariable, because it requires information from the subclass, i.e. the term field.

For clarification and not to overload the meaning of things it would be great if we could add an attribute `reduction` on the variable which stores the `reduction` math KISAO term of the reduction. This would
- separate the DimensionReductions from the DependentVariable
- allow to apply dimension reductions on DependentVariables ! which is currently not possible because the term is used in both contexts (DependentVariable definition and Dimension reduction)
- allow validation and checking (because the `reduction` field is restricted to KISAO terms with reduction math meaning

I am open for a different name of the attribute, the important part is the separation from the `term` attribute of the DependentVariable here.

**Comment by luciansmith** [comment]
I would be happy to rename 'term' so it more clearly could apply to either type of function (i.e. dependent variable or a dimension-reducing function), but unless there's some context where you need both (and I can't think of one), I think there should only be one attribute.

As far as the AppliedDimensions inheriting from the base or the derived class, I'm kind of iffy on changing things.  I think there might be some contexts where you might want an AppliedDimension with no 'term', and there's no real penalty from allowing it on the base class.

(That said, I'd probably be happiest at this point in just collapsing the whole thing back down to just a single class.  I don't think anything is gained by defining both Variable and DependentVariable.  It seems kind of big for a last-minute change, though.)

**Comment by matthiaskoenig** [comment]
I could imagine many use cases where you need both.
- E.g. calculate the rate of change of a variable in a stochastic simulation and then reducing via averaging over the stochastic runs
- E.g. sample a parameter from a distribution and calculating metabolic control coefficients, then averaging over the samples,
- ....
Basically we cannot do any of this with the current solution because the term would be required for both.

I am okay with the split in Variable and DependentVariable which somehow clearly indicates the extension in L1V4.

**Comment by luciansmith** [comment]
Wouldn't you create a variable with one of them, and then reference that variable with the next?  Doing everything at once seems a bit sketchy to me.

x = rateOfChange(S1)
y = mean(x)

**Comment by matthiaskoenig** [comment]
I think I would do that at the same time. 

Main issue I have here is that the Reduction is not clearly separated from the DependentVariable concept which makes it very difficult to comprehend (especially all the nuances).
For me it would be much cleaner if the variable just has a reduction which would link to a `Reduction` class containing all the information. This simply breaks down to: apply the reduction by applying the function to the indicated dimensions.
I.e. 
```
Variable
  id: SId
  modelReference: SIdRef
  target: TargetType
  symbol: string
  target2: TargetType
  symbol2: string
  term: string
  reduction: SIdRef

Reduction:
  id: SId { use="required" }
  function: kisao
  listOfAppliedDimensions
```
This would also make it much easier to indicate which tools support Reduction and with what subset of KISAO functions.
My experience with overloading things in SED-ML to also cover other use cases is that it makes things much more complicated to comprehend instead of being more explicit. Having all information for the reduction in the Reduction object makes it so much clearer.
We can still change this, I am just starting implementation for this and nobody else is having support so far (besides @luciansmith in tellurium probably).

**Comment by luciansmith** [comment]
All told, I think I'm not super in favor of this change, but I'm also not a current editor.  @jonrkarr @fbergmann @nickerso Tomas:  opinions?  If we're going to change things, I think the options are:

Variable vs. DependentVariable:
a1) Leave things as they are.
a2) Merge DependentVariable back into Variable; just give it new optional attributes.
a3) Move ListOfAppliedDimensions to DependentVariable

(Also, maybe rename DependentVariable, as it no longer quite means what it used to)

Attributes:
b1) Leave things as they are (use 'term' for all functions).
b2) Add a new 'reduction' attribute and let people use both it and 'term' at once.
b3) Add a new 'reduction' attribute but make it mutually exclusive with 'term'.

My own ranked preferences:
a1, b1:  Best
a2, b1:  Best if we're OK with a last-minute change.
a2, b3:  OK.

**Comment by jonrkarr** [comment]
Given that this is a new feature of SED-ML, I think its fine to make changes. Actually this is the ideal time before anyone starts using it and issues get locked in.

In general, I'm in favor of clarity and concreteness. I haven't followed this part of SED-ML closely. I defer to those that are.

**Comment by fbergmann** [comment]
Its a bit unfortunate, that this comes this late, as it will definitely make us miss the JIB deadline, and so delaying the release of the spec by probably another year. So I was leaning to `a1, b1`. 

But then again, its already been that many years, so what is another delay. The borders of `variable` and `dependendVariable` are becoming fluent. So i'm fine with `a2`. As for the b`s, why would you prohibit the usecase that matthias was outlining with reducing something derived by a term?

**Comment by jonrkarr** [comment]
I don't think this needs to require missing the deadline. I think it's OK to submit the paper by the deadline, and then make a change prior to publication. This is one of many improvements in the new version. I don't think modifying this would substantially change peer review.

**Comment by fbergmann** [comment]
like i said, i'm fine with making the `a2` change, not just sure whether `b2` or `b3` is the best option. we need to wait for @luciansmith  or @matthiaskoenig to come to a consensus.

**Comment by matthiaskoenig** [comment]
I don't think this is an issue for the JIB deadline. These are just smaller things coming up during implementation and would be great if we fix these for clarity. I just talked with Lucian and he tries to write things down.

**Comment by luciansmith** [comment]
OK!  Talked to Matthias, collapsed the classes, and added a new 'dimensionTerm' to Variable.

As Matthias suspected, the resulting write-up was indeed cleaner:  now there is one group of attributes that define 'what's the target' (taskReference and modelReference), one group of attributes that define 'what Thing are you after?' (symbol, target, symbol2, target2, and term), and one attribute and set of child objects that define 'now how do you reduce the dimensionality?' (dimensionTerm and AppliedDimension objects.

I like the result!  I obviously haven't tried to implement support directly for this, but having done so with the previous version, I can see how this is going to be a little cleaner.  Still on target for a July 31st submission.  I hope.

@matthiaskoenig , @jonrkarr , @fbergmann, @nickerso, and Tomas:  not going to quote the whole thing here, but if you can read over the 'Variable' section in https://github.com/SED-ML/sed-ml/blob/master/specification/level-1-version-4/sed-ml-L1V4.pdf to make sure I didn't say anything weird, that'd be wonderful.  Thank you!

**Comment by fbergmann** [comment]
I had a read through the variable section, and it looks fine to me. It is a big change so late, but it still lets us do every thing you need, a couple of smaller rewordings: 

•	‘the minimum eigenvalue’ -> the smallest eigenvalue
•	Listing 2.6: target="\changed{Path} TO… -> target=”PATH TO MODEL ELEMENT / ATTRIBUTE WITH CHANGED VALUE..” (any reason this is all in caps?)
•	Term definition: this is a new attribute on ‘Variable’ so it would seem odd that ‘urn:sedml:symbol:time’ can be used for backward compatibility. On the variable itself time would only be used for symbols. No reason to ever use it on the term. So I would end the sentence after `kisaoID`. 
•	`dimensionTerm`: overrun of line into margin for KisaoID

Anyway, thanks for getting this done. I’ll be traveling until the 3rd with only intermittent internet connection, but I’m happy that this is going out.

**Comment by luciansmith** [comment]
@fbergmann ; Fixed!  Thank you.
