### ISSUE TITLE
Add sentence about allowed KISAO terms in AppliedDimensions

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#189]
A sentence clarifying the subset of allowed aggregation/reduction functions with AppliedDimensions should be added. I.e.

> Only children of http://www.biomodels.net/kisao/KISAO#KISAO_0000824 are allowed as aggregation functions

Also multiple typos: "A AppliedDimension" -> "An AppliedDimension" in the spec.

**Comment by luciansmith** [comment]
Done!  Went with 'should' instead of 'must' since we're not requiring KISAO at all at this point (I think?) and the structure of KiSAO might change in the future.
