### ISSUE TITLE
Description of `listOfAppliedDimensions` attribute missing on variable

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#190]
The `listOfAppliedDimensions` is not explained on Variable. Some sentences should be added in which contexts AppliedDimensions can be used. As I understand things only two use cases are possible:

* Dimension reducing functions can be applied in two contexts. First to reduce data from RepeatedTasks and nested RepeatedTasks which requires the taskReference of the variable to be set and to be a reference to a RepeatedTask. All AppliedDimensions must have the target set and reference either one of the possibly nested RepeatedTask Sids or the Task or one of its subtasks within the RepeatedTask.
* Second to reduce data from a multi-dimensional DataSource in a DataGenerator which requires the target of the variable to be set to reference the respective DataSource. The AppliedDimensions must have the dimensionTarget set to a NuMLIdRef referencing a dimension of the data."
* "If the listOfAppliedDimensions contains 2 or more AppliedDimensions the reducing function is applied on an element-by-element basis."

**Comment by luciansmith** [comment]
Mostly fixed earlier, but one more update to address the above list.  Should be done!
