### ISSUE TITLE
Sum and product are still missing from KISAO for the AppliedDimensions

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#192]
`sum (ignoring NaN)` and `product (ignoring NaN)` are still missing from KISAO to have full coverage of the L1V3 reducing math functions.

I will fix this as part of the updates in 
https://github.com/SED-ML/KiSAO/issues/93

Also we should add sentence to the `min`, `max`, `sum` and `prod` spec description which lists the KISAO term for the new functions.

**Comment by luciansmith** [comment]
Nothing needs to be changed in the SED-ML spec itself, right?  I'm closing this, but if I'm wrong feel free to re-open.

**Comment by matthiaskoenig** [comment]
Is not important for the spec. Just opened this so we don't forget.
