### ISSUE TITLE
Allow a few more MathML terms

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#198]
In SBML L3, there were some new MathML terms allowed in the math.  Since we tend to use the same parser, it might be nice to allow these new terms in SED-ML as well.  The terms are:

max
min
quotient
rem
implies

I would not be surprised if libsedml already assumed that SED-ML allowed these terms.

Obviously, max and min would be the versions that take multiple scalar arguments, vs. the dimension-reducing min and max that we encode elsewhere.

**Comment by matthiaskoenig** [comment]
I agree. Makes sense to have this synchronized. What about the distrib
MathML ?

**Comment by luciansmith** [comment]
The distrib csymbols are different in SED-ML than they are in SBML; I assume this was because people didn't want to make SED-ML core dependent on SBML.  I think the implementation can be pretty similar, but I haven't looked at it in detail.

**Comment by luciansmith** [comment]
Contacted Falk, who said we could submit an updated version but not as part of the review process--we had to submit it today.  So I made this change!  Hope nobody gets too upset at me ;-)

**Comment by matthiaskoenig** [comment]
Thanks for the update.
