### ISSUE TITLE
Plot features for L1V4

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#20]
# Issue
In L1V3 only a very limited subset of plot features is available. These features have to be extended to cover additional use cases and make outputs more reproducible.

# Proposals
L1V4 will bring major updates to the plotting capabilities. Here an overview of the latest proposal. This is still work in progress (the curves and plot2D are almost ready, the new Surface classes still need discussion)

`Plot`
https://docs.google.com/drawings/d/11o_WNXsAs5jPaGIa06qY-cVBsJZQdSFuLnRQes6GSJU/edit
`AbstractCurve`,` Line`, `Marker`, `ShadedArea`, `Fill`  
https://docs.google.com/drawings/d/10MQj_b3lBT-jX30Ki1sH_qnB1VC1Y-DcttUttlWQA98/edit
`AbstractSurface` and subclasses  
https://docs.google.com/drawings/d/1NYhW0PVjH7h-hoMz9wJtai1hpxr_Anv26inBY3CJMKY/edit

The UML diagrams are the reference for now. Decisions should be reflected in the diagrams. Below additional information of importantce

SymbolStyles: 
- Square
- Diamond
- Triangle
- Circle
- XCross
- Plus
- Star
- TriangleDown
- HDash
- VDash
- None

LineStyles: 
- Solid
- Dash
- Dot
- DashDot
- DashDotDot
- None

Colors:
- RGBA (i.e. 4 hex numbers)

## Open points for discussion
There are still some points to decide. Below the open things.

### The log element on Curve: 
Somehow we have to resolve the logX, logY issue
Remove logX, logY?
Add log on Plot2D (https://sourceforge.net/p/sed-ml/mailman/message/25880621/ )

### named colors? 
Should named colors be allowed. Solution could be to allow a clearly defined subset:
Herbert wanted named colors like: http://matplotlib.org/examples/color/named_colors.html another list can be found here: https://msdn.microsoft.com/en-us/library/system.drawing.knowncolor(v=vs.110).aspx 
Preferred mapping for Frank to implement: http://www.w3schools.com/cssref/css_colors.asp

###  Multiple y-axes on plots?
Do we want that? Should this be supported, or for now leave it out. This is not very common.

**Comment by matthiaskoenig** [comment]
What is missing are Barplots. Can we add this? 

It takes the same DataGenerator like a normal curve, but just plots the bars. Only needs an additional attribute width (or a second DataGenerator width, which defines the width for all data points).
This is very easy to implement and is a very common plot type.

**Comment by luciansmith** [comment]
I agree we should add bar plots.

Would it work to add 'bar' to the list of LineStyles?  Or do we need something else?

**Comment by matthiaskoenig** [comment]
We need something to define the width of the bars. These could also be different for the different data points. I think it should be something like
```
BarCurve (Curve):
  widthDataGenerator
```

I put in brackets the parent class. The marker attributes of the curve would be interpreted as bar attributes (linecolor & fillcolor will than be outline and fill of the bars). The xData and yData of the curve would be the center of the bar.

**Comment by matthiaskoenig** [comment]
An important thing in plotting is which curves are on top of which, i.e. the order in which the curves should be plotted. This becomes for instance important when plotting filled areas, or data with curves (where the data should be on top).
We need something like an optional `order` attribute on curve as a way to specify the order in which to plot the curves.

**Comment by fbergmann** [comment]
i'm fine with an optional order attribute, but I would rather not have to
sort the file and instead just plot them in the order they are?

**Comment by matthiaskoenig** [comment]
Yes, I am also good with plotting in the order they are (this is mainly how I am doing this now). But than we have to define that the natural order of listOf* in the file means something somewhere in the spec. 

As I remember there was a lot of discussion about the listOf* are unordered in XML and tools can in principle load and write the listOf* in any order they want.

**Comment by jonc125** [comment]
Child elements *are* ordered in XML, but most COMBINE specs state that the order doesn't matter in most cases.

**Comment by matthiaskoenig** [comment]
Closing this. Plotting feature subset for L1V4 has been decided. Part of spec, library and implementations exist.
