### ISSUE TITLE
Dealing with multi-dimensional data

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#21]
# Issue
Handling multidimensional data in SED-ML is not defined, despite tasks/repeated tasks creating such data. Important features necessary to work with multi-dimensional data is
* defining the dimensionality of the data/dataGenerator/variable and dimensionality of return results from simulations and tasks
* indexing over subdimensions of the data (i.e. slicing over different dimension)
* extracting subsets of the data along a dimension
* applying math along one of the dimensions 

L1V4 must define a way to work with higher dimensional data, i.e. 
* how to generate them with nested repeated task
* how to create DataGenerators from them
* how to select subsets of the data (along the different dimensions, indexing)
* how to calculate aggregate math like mean, std on subsets of the data
* how to plot the data in surfaces (and plot2D)

# Examples
for instance with multidimensional arrays
* `A0D` with `shape (1, )`, i.e. scalar (zero-dimensional array)
* `A1D` with `shape (N1, )`, i.e. one-dimensional array with `N1` elements
* `A2D` with `shape (N1, N2)`, i.e. two-dimensional array with `N1` elements in first dimension, `N2` elements in second dimension
* `A3D` with `shape (N1, N2, N3)`, i.e. three-dimensional vector with `N1` elements in first dimension, `N2` elements in second dimension, 'N3` elements in third dimension

# Proposals
Extend the core SED-ML classes to keep track of the dimension information. This would provide a clean way to handle multi-dimensional data and help in the implementation. This would also resolve many uncertainties on how to handle repeatedTasks of repeatedTasks.

## Dimensionality on Parameter
* a `Parameter` is always scalar, i.e. `A0D`

## Dimensionality on Range
* a `Range` is always 1D-array, i.e. `A1D`
    * using a range in a repeated Task results in N1 repeats
    * all ranges on a repeated Task must have the same length, i.e., N1 must be identical so these are run through together

## Dimensionality on DataSources
* a `DataSource` has the dimension according to the dimensionDescription and the applied slices or IndexSets. I.e. if an `A3D (N1, N2, N3)` is loaded and an indexSet selection is applied on N2 dimension, than the dimensions of the DataSource is `A2D (N1, N3)`. The DataSource clearly defines the dimensionality of the returned array.

## Dimensionality on Tasks
Some classes get an additional attribute to indicate their respective dimensionality, like the simulation must indicate the length of the results array (this is implicit in the definition of the Simulation, but would mean the following:
```
Simulation:
    dimensionality: integer (dimensionality of simulation result)
    ...

OneStep(Simulation):
    dimensionality: 0 (scalar, i.e length of result is one value)
    ...

TimeCouseSImulation/NonUniformTimeCourseSimulation(Simulation):
    dimensionality: 1 (1D, i.e. length of result is length of time points)
    ...

SteadyState (Simulation):
    dimensionality: 0 (scalar, i.e length of result is one value)
    ...
```
Tasks must define their dimensionality!, not the AbstractTask, only Task. This is the added dimensionality by the task in addition to the simulation dimensionality.
```
Task(AbstractTask):
    dimensionality: 0 (scalar), no added dimensionality

CalculateEigenvectors(Task)
    dimensionality: 2 (2D array which contains vectors)
CalculateEigenvectors(Task)
    dimensionality: 1 (1D array of eigenvalues)
CalculateJacobian(Task)
    dimensionality: 2 (2D array of jacobian)
CalculateElasticity(Task)
    dimensionality: flexible (2 if no reaction or parameter set, 1 if either set, 0 if both set)
CalculateSensitivity(Task)
    dimensionality: flexible (2 if no reaction or parameter set, 1 if either set, 0 if both set)
CalculateMoietyConservationLaws(Task):
    dimensionality: 1
```
The dimensionality of the task results depends on the simulation dimensionality, the task dimensionality and on how many nested repeated tasks were used to create the results.
For a Task the dimensionality of the result is:
`dim_simulation + dim_task`
where the left most index is simulation index, than the task index, i.e. 
* a Task with Steady state has dimensionality `0 + 0 = 0`, the result is a scalar
* a Task with TimeCourseSimulation has dimensionality `1 + 0 = 1`, the result 1D array, with the first (and only) index being the time index
* a JacobianTask with OneSte has dimensionality `0 + 2 = 2`, the result is a 2D array
* a CalculateSensitity (with no reaction or parameter, i.e. dim=2) with Timecourse has dimensionality `1 + 2 = 3`, calculating all sensitivities along the timecourse, with indexing on first dimension being simulation time, 2 and 3 the respective sensitivity for the given timepoints

Every nested `RepeatedTasks` adds a additional dimension with the length of the 1D range, i.e., 
`dim_simulation + dim_task + dim_range1(repeatedTask) + dim_range2(repeatedTask) + ....`

 * a RepeatedTask of a Task with TimeCourseSimulation has dimensionality, i.e. `RepeatedTask(Task(TimeCourseSimulation))` has `1 + 0 + 1 = 2`, the result 2D array, with the first index being the time index, second index over the repeatedTask
 * a RepeatedTask of a RepeatedTask of a Task with OneStep has dimensionality, i.e. `RepeatedTask(RepeatedTask(Task(OneStep)))` has `1 + 0 + 1 + 1 = 3`, the result 3D array, with the first index being the time index, second index over the range of the inner repeatedTask, third index over the outer RepeatedTask

## Variables
The dimensionality of variables is flexible and depends on the referenced task, i.e. 
* a `Variable` has the dimensionality of the task which produced the results.

**Math on variables and listOfVariables**
* all variables in a listOfVariables must have the same dimensionality and the same length of all indices for all dimensions, i.e. the n-D arrays of all variables must have the same size.
* all math (with exception of aggregate functions, i.e. min, max, sum, prod) is calculated in a element wise manner, i.e. for every element of the n-D variables which are used in the math.

## DataGenerators
Classical DataGenerators have the same dimensionality/size like the variables in the list of variables, i.e. they can also be a n-D array.
In addition the DataGenerator is extended to allow for slicing of subsets of data analog to the slicing in DataSources, i.e.. This is called dimensionReduction and allows to cut out a lower dimensional cube, i.e. a (n-1) cube from a full (n) dimensional array. 

TODO: finish how the DataGenerators would work, how to index in the nd array
```
DataGenerator():
    |
    -- listOfDimensionReductions

DimensionReduction():
    dimension: 
    index: 

```

# Related Issues
* Discussion about the topic can be found in https://groups.google.com/forum/#!topic/sed-ml-discuss/5bHa-wliIVU

**Comment by jonrkarr** [comment]
We've dealt with this with BioSimulators for variables, data generators, and reports. The need to support multidimensional results is one reason we've decided to output reports to HDF5. As part of the curation of algorithms, we also track the dimensionality of their outputs, using SIO to describe the dimensions they produce.

**Comment by luciansmith** [comment]
I believe that the current version of the spec, particularly with https://github.com/SED-ML/sed-ml/commit/517c093e8e320b9d6a3dd508f1e7beaadb15a27b and https://github.com/SED-ML/sed-ml/commit/a00242bfaabc113dcd6fee3c191e232d5fb7a68d largely addresses this issue, without adding new 'dimensionality' elements to anything.

@matthiaskoenig : do you still see either a need for further clarification, or for explicit demarcation of dimensions for future versions of SED-ML?  We can either close this if you're happy, make further edits, or tag it L2.

**Comment by jonrkarr** [comment]
One thing that hasn't been addressed is annotation of the excepted dimensionality of results as @matthiaskoenig outlines above. I agree this is important. I think the dimensionality is implied by the simulation algorithm (KiSAO term) and target+symbol (e.g., Jacobian; now KiSAO term). As a result, I think this can be addressed outside of SED-ML. KiSAO could, but doesn't capture this information. Instead, we've collected this information as part of our curation of simulation tools.
