### ISSUE TITLE
Distributions (define distributions & use values from distributions in repeatedTasks)

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#23]
# Issue
It would be great if one is able to set values using a statistical distribution. 

Mainly sampling parameters and initial values from distributions and specifying how to sample. 
How to sample from multiple distributions at the same time? Or multi-dimensional distributions, i.e. with correlation matrix? How to specify the sampling on multi-dimensional distributions (random, Latin-Hypercube Sampling)

# Examples
- generate a set of parameters from a given distribution to use them in a repeatedTask

# Proposals
Create a new type of DataGenerator which creates data from a distribution.
```
DistributionDataGenerator(DataGenerator):
    shape: DimensionDescription
    distribution: string (normal, lognormal, .. defined vocabulary terms)
    seed: int {use: optional} (random generator seed)
    |
     --- listOfParameters: list<Parameter> parameters of distribution
```
Concrete example
```
DistributionDataGenerator(DataGenerator):
    shape: (200, 1)
    distribution: normal
    seed: Normal
    |
     --- listOfParameters: mu=1.0, sigma=10.0
```
creates 200 random values from normal distribution.

The shape defines the dimension of the data output, distribution the distribution type

# Related issues
* User defined function definitions ( #5 )
* See also how SBML-distrib is handling this and look for guidance
* This would go in hand with the iteration over data generators ( #48 )

**Comment by luciansmith** [comment]
Handling this by extending MathML instead!
