### ISSUE TITLE
Parameter Estimation/Fitting

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#26]
# Issue
Parameter estimation/fitting with SED-ML is an open question and would be a great use case for data.

# Examples
* read experimental datasets and parametrize the model based on the data, i.e. reading data, parameter fitting, using fitted parameters for simulations/tasks

# Proposals

**Comment by matthiaskoenig** [comment]
Here the discussion on this
https://docs.google.com/document/d/1rrs0fYuKFr4fgL1b7eGwSnaLhRPW6NdXwAaJY0ZN_WY/edit#heading=h.61sixvmnpg15

**Comment by luciansmith** [comment]
https://docs.google.com/drawings/d/1pa6MURTa2vuRlcdC9WW2l_b9w6Gj_V-L0yyJe4ZwNRs/edit

**Comment by luciansmith** [comment]
This is in and finished, as far as I know.
