### ISSUE TITLE
New tasks: Eigenvalues, Jacobians, Sensitivities

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#27]
# Issue
* Talked about how to get things like eigenvalues, jacobian, etc.
* Decided that adding new tasks for these is the way to go
* These tasks will make various vectors and matrices available to the data generators that which have variables which reference the tasks.
* Will probably need new symbols and/or MathML in order to be able to pull out and use the appropriate data. Will leave this until such time as implementers start doing things with these tasks.

# Examples
* calculating Jacobian, or sensitivities on a given model

# Proposals
Adding additional tasks. See for first proposal 
https://docs.google.com/drawings/d/1AvL5kGmCjYqw757a07A2Osc_9vZNVd7ySG3KqhhCX1I

**Comment by luciansmith** [comment]
It was decided to go with new KiSAO terms instead for this.
