### ISSUE TITLE
Figures and tables together in spec

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#29]
Many UML figures are very empty (only one class). It would save lot of space and make the spec much more compact by just putting the figure and table of such classes next to each other.
Just putting this down so I don't forget it.

**Comment by matthiaskoenig** [comment]
This does not improve the readability, but creates more confusion. Clear separation of table with attributes and uml diagram is the better solution.

**Comment by luciansmith** [comment]
I actually don't think the tables are useful, either.  At least not if the UML is clear.  (They were helpful when the UML was broken ;-)

**Comment by matthiaskoenig** [comment]
The useful thing about the tables is that they link to the definition of the attributes and elements. I.e. they provide a fast lookup of the definitions.
