### ISSUE TITLE
Define DataGeneratorRef, TaskRef, SimulationRef

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#35]
We should define additional primitive types which would make the spec much clearer and easier to understand.

Currently, there is only `SIdRef`, but we should introduce respective Refs for linking to certain subsets of SED-ML, i.e.

`TaskRef`: Is of type `SIdRef` but only allows `SId` from `Tasks` in the `listOfTasks`

Same for `SimulationRef`, `DataGeneratorRef`, ...
This would make the UML diagrams much clearer, also the text would be much cleaner.

Currently, there is a lot of the following in the spec:

> The  \concept{zDataReference} is a mandatory attribute of the \hyperref[class:surface]{Surface} object. Its content refers to a dataGenerator ID which denotes the \hyperref[class:dataGenerator]{DataGenerator} object that is used to generate the output on the z-axis of a \hyperref[class:plot3D]{3D Plot}.
The \concept{zDataReference} data type is \code{SIdRef}. However, the valid values for the \concept{zDataReference} are restricted to the IDs of already defined \hyperref[class:dataGenerator]{DataGenerator objects}.

which could be

> The \concept{zDataReference} is a mandatory attribute of the \hyperref[class:surface]{Surface} object of data type \hyperref[sec:DataGeneratorRef]{DataGeneratorRef}.

Personally, I would love to introduce these right now while updating the L1V3 spec. If there is no quick agreement we should do this in L1V4.

**Comment by luciansmith** [comment]
I'm not sure about this one.  It's possible, but it's unclear to me that it would be actually more concise or easier for a naive user to understand.  I could probably go either way, I guess?

I will point out that your re-wording of the zDataReference text actually dropped important information, IMO.  Even with your new DataGeneratorRef type, I think you'd still need something like the following:

> The  \concept{zDataReference} is a mandatory attribute of the \hyperref[class:surface]{Surface} object of type \code{DataGeneratorRef}. Its content refers to a dataGenerator ID which denotes the \hyperref[class:dataGenerator]{DataGenerator} object that is used to generate the output on the z-axis of a \hyperref[class:plot3D]{3D Plot}.

Without the new type, we could still clean things up:

> The  \concept{zDataReference} is a mandatory attribute of the \hyperref[class:surface]{Surface} object. Its content refers to a dataGenerator ID which denotes the \hyperref[class:dataGenerator]{DataGenerator} object that is used to generate the output on the z-axis of a \hyperref[class:plot3D]{3D Plot}.
The \concept{zDataReference} data type is \code{SIdRef}, and must refer to a \hyperref[class:dataGenerator]{DataGenerator} object.

**Comment by matthiaskoenig** [comment]
Yes, you are right probably we are not saving so much in the text, but it would make the UML much clearer.
Instead of 
`dataReference: SIdRef`

you have than
`dataReference: DataGeneratorRef`

which makes clear what is referenced in one look in the UML without the need to lookup things and see for evers SIdRef which subset of SIds is allowed in the respective context.

**Comment by matthiaskoenig** [comment]
This is not necessary. Does not give additional functionality, but only a bit more clarity.
Closing this.
