### ISSUE TITLE
Access Derivatives of Variables

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#4]
# Issue
SED-ML provides a simple way to reference variables using XPath, but there is no way to reference the first (or higher-order) derivatives of those variables (without changing the model), despite the fact that these derivatives of state variables are likely to be computed by solver software.
[`https://sourceforge.net/p/sed-ml/feature-requests/6/`](https://sourceforge.net/p/sed-ml/feature-requests/6/)

# Examples
* time-derivatives: having Species `S1` and `S2` in model. One wants to plot `dS1/dt` or `dS1/dt + dS2/dt`
* ? are there other derivates than time derivates important here? 

# Proposals
- indicating via a csymbol what we want (see Frank's comment below)

# Related Issues
* Jacobian and Sensitivities( #27 )

**Comment by luciansmith** [comment]
Maybe we could borrow the SBML L3v2 csymbol 'rateOf' for this?

**Comment by matthiaskoenig** [comment]
This can be handled via the Jacobian and Sensitivity Features we are planning. 
In my opinion this are the derivatives of interest and would be handled by what we discussed during HARMONY.

**Comment by fbergmann** [comment]
I'd rather see something like the derived variable i proposed in maastricht
... where we indicate via csymbol what we want ... this would be more
flexible than just referring to rateOf ... again the philosophy from back
in the day was ... add as little things as possible with the biggest bang
for the buck ...

besides ... rateof for cellml might not even be a rate with respect to time
... so really scary from an sbml point of view

**Comment by luciansmith** [comment]
This is being solved with KiSAO terms.
