### ISSUE TITLE
CellML based example which can be run with software (opencor)

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#42]
We need an CellML example which can be executed with existing software, i.e. opencor.
The current leloup-cellml cannot be executed and does not work.

I would prefer a simple timecourse simulation with one model without changes to the model. But if more complex things are supported in opencor this would also be nice.

**Comment by nickerso** [comment]
I suggest we use one of the models from the "OpenCOR tutorial": https://models.physiomeproject.org/e/430. The Lorenz attractor is a nice small example: https://models.physiomeproject.org/e/430/lorenz.cellml/view. I'll see if I can get one together that works in OpenCOR and the SED-ML Web Tools.

**Comment by matthiaskoenig** [comment]
Lorenz example is great and visual pleasing.

**Comment by nickerso** [comment]
There is now an archive available under https://models.physiomeproject.org/e/4c7/ which, at least to my eyeballs, gives the same results in OpenCOR and the SED-ML Web Tools.

Now we just need to update the example in the spec :)

**Comment by matthiaskoenig** [comment]
Hi @nickerso,
I created the analog SBML Lorenz model and simulation experiments.
Examples are updated in the spec.
https://github.com/SED-ML/sed-ml/raw/master/specification/level-1-version-3/sed-ml-L1V3.pdf

Unfortunately, the Lorenz example is the worst possible example :/. The problem is that it shows deterministic chaos, i.e., depending on the actual starting condition the outcome is very different.
Even when setting values of 1.0 for starting the one implementation has internal
1.000000000000000000000001
the next one
0.999999999999999999999999
which results in completely different trajectories over time.

You can see this in the spec
Fig A15 (lorenz sbml SED-ML webtools)
Fig A16 (lorenz sbml SED-ML tellurium)
Fig A17 (lorenz cellml SED-ML webtools)
Fig A18 (lorenz cellml SED-ML opencor)
All are exactly the same simulation experiments with the same mathematical model, but give different results due to numerical errors resulting in different deterministic chaos.

Is also a result, but not a good example for a reproducible simulation experiment.

**Comment by matthiaskoenig** [comment]
Just to add. You can see nicely how everything is almost identical until ~15 time units in all simulations than the small numerical differences between implementations send the trajectory somewhere different.

**Comment by matthiaskoenig** [comment]
@nickerso Any opinion on this? Not sure what to do with the CellML example.
The two options are:
- [1] use lorenz like it is in the example section right now and discuss why different implementations will result in different simulation results (deterministic chaos)
- [2] use another CellML example, but than I would need an archive for that example. Preferable not to complictated so I can translate the model to SBML rapidely

**Comment by nickerso** [comment]
I think its a nice example and a good discussion to have somewhere, but probably not in the spec for a standard that is all about accurately reproducing things :) I'll come up with a new example.

**Comment by nickerso** [comment]
I have updated that workspace to use the Van der Pol oscillator model instead. Hopefully still interesting while being more deterministic and less chaotic :) You can get a new archive from https://models.physiomeproject.org/e/4c8, which I've tested in OpenCOR and the SED-ML web tools to both look the same (although that doesn't say much given how badly the last example compared!). The math is pretty straightforward, just two ODEs: https://models.physiomeproject.org/e/4c8/vanderpol.cellml/cellml_math, although perhaps this one is already in biomodels somewhere...

**Comment by matthiaskoenig** [comment]
Example is updated in spec and examples.
Still some issue getting the SBML version running with SED-ML webtools, but otherwise everything is in the spec
https://sourceforge.net/p/libsedml/tickets/15/

Also some minor issue running the L1V3 archive (but this should be fixable very easily)
https://github.com/opencor/opencor/issues/1429
Also can't export images from OpenCOR yet, but already fixed and just waiting for next snapshot
See https://github.com/opencor/opencor/issues/1123
Until this is available I do the screenshot.

**Comment by matthiaskoenig** [comment]
The example is in the spec just added the remaining comments for reference.
