### ISSUE TITLE
Update the homepage with the L1V3 information

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#50]
Just opening this, so I don't forget.
This includes
* [x] link to newest spec L1V3, create and add L1V4 draft 
* [x] update UML diagrams on homepage
* [ ] HTML version of spec
* [ ] L1V3 example page with Combine Archives, Results & links for direct execution in SED-ML web 
tools and tellurium web
* [ ] update news section
* [ ] upload specification to `http://identifiers.org/combine.specifications/sed-ml.level-1.version-3` like stated on frontpage

**Comment by matthiaskoenig** [comment]
@nickerso Could you take care that the spec is uploaded to `http://identifiers.org/combine.specifications/sed-ml.level-1.version-3`

**Comment by matthiaskoenig** [comment]
Thanks @nickerso 
Could you also update the following information:

[1] http://co.mbine.org/standards
in the SED-ML section there is still the link to

> The latest stable specification is Level 1 Version 2. 
=>  change to L1V3

Could you also update the following sentence:
> APIs are available to help implementing support: jlibsedml in Java and libSedML in C#. 
==>
APIs are available to help implementing support: libSedML in C#, libSEDML(https://github.com/fbergmann/libSEDML) in C++ with swig bindings for python, java, perl, R and ruby, and jlibsedml in Java.

 [2] http://co.mbine.org/standards/sed-ml
> A draft proposal is available for SED-ML Level 1 Version 3. 
A draft proposal is available for SED-ML Level 1 Version 4. 

In the history section of the page update the link to the google group
sed-ml-discuss mailing list (https://lists.sourceforge.net/lists/listinfo/sed-ml-discuss/).

**Comment by nickerso** [comment]
changes made - for the L1V4 link I just linked to the github issues rather than a draft spec, as I think that is more useful...
