### ISSUE TITLE
Calculating math over Repeated Tasks (mean, sum, min, max, std, ...)

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#53]
# Issue
it must be possible to easily calculate summary functions over the runs of the stochastic simulation or over repeatedTasks in general. Things like mean, variance, std, min, max, ...
Currently, there is no way to get such information.

# Example
- calculating mean & std of a stochastic simulations
- calculating min and max concentrations over a parameter scan

# Proposals

# Related Issues
- stochastic simulations ( #22 )
- dealing with multidimensional data ( #21 )

**Comment by luciansmith** [comment]
This is now possible with the DependentVariable object combined with new KiSAO terms.
