### ISSUE TITLE
Clarifications about NA values needed

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#56]
# Issue
Currently it is undefined what happens with NA values. Often subsets of data is NA. But a simulation result could also result in NA values.
* what happens in math using NA (all derived calculations should also be NA for the respective elements in the DataGenerators
* how should this be displayed in plots? Discontinuities? Warnings?

I added basic clarifications about the reading of NA for L1V3, but this must be stated clearly in the spec. 

# Proposal
* NA values can occur in `DataSources`, `SimulationResults`, `DataGenerators`
* all Math on NA generates NA as output, if math is element-wise, element-wise NA evaluation, if math over array result is NA if at least one value is NA (or better provide a skip NA attribute)

**Comment by luciansmith** [comment]
This is what we have currently about NA.  I don't know when it was added (section 3.1.4):

"NA (not available) values can occur within a simulation experiment. Examples are missing values in a
DataSource or simulation results with NA values. All math operations encoded in MathML in SED-ML
are well defined on NA values.

NA values in a Curve or Surface should be ignored during plotting"

Is this sufficient, or do we need more?

**Comment by matthiaskoenig** [comment]
Sounds good to me. 
A sentence on the reducing math functions is required. Basically things like `mean` could either ignore NaN or result in Nan. That is why there are different functions for this for instance in numpy, i.e. `mean` vs `nanmean`
https://numpy.org/doc/stable/reference/generated/numpy.mean.html
https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html#numpy.nanmean

I would suggest to use the classical `mean` i.e. a reducing math operation on a vector with a NaN results in NaN.

**Comment by luciansmith** [comment]
If we go with Jonathan-style 'add NaNs everywhere', I think we would definitely want the 'ignore NaNs' mode.  See https://github.com/SED-ML/sed-ml/issues/77#issuecomment-859957234 for an example:  right now, Biosimulators fills out all the blanks with NaNs, meaning that the average of 'S1,r1' would be 5.87, and the average of 'S1,r2' would be NaN (unless we said to ignore NaNs).

If the only time you end up with a NaN is because of a mathematical calculation resulted in a 0/0, we'd want to go with 'don't ignore NaNs'.

Given that I see calculations involving 0/0 happening a lot less frequently than people doing NaN-padding, I'm inclined to go with 'ignore NaNs'.  (The only other alternative I see is to forbid NaN-padding, which seems a bit fraught.)

**Comment by matthiaskoenig** [comment]
I am okay with doing "ignore NaN" math. I am not sure the NaN padding is a good idea. This seems like an implementation detail to make it easier to work with the data for Jonathan, but I am not sure we should make this a general requirement.

**Comment by luciansmith** [comment]
Oh, since the new system just says 'go look at KiSAO', I would say that it's KiSAO itself that should define which min/max/mean/etc. to use.

**Comment by luciansmith** [comment]
So, the KiSAO terms now mention that you should skip NaNs , and if we put back in min/max, we'll mention ignoring NaNs there, too.  Also, cf https://github.com/SED-ML/sed-ml/issues/77 I added:

"It is left up to interpreters how to store or output ‘ragged’ matrices, where the data in some dimensions
might not have the same lengths as each other. One practice is to leave the data in this uneven state;
another option is to fill out the ‘missing’ data with NaNs. The only requirement is that mathematical
operations should not be affected by this choice. For example, the ‘mean’ of a vector should be the same
whether or not it was extended with NaNs."

I think this addresses everything, so I'm closing this, but feel to re-open with any other suggestions.
