### ISSUE TITLE
L1V3 example archives with single metadata file

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#57]
The current L1V3 archives contain multiple metadata files. There should only be a single metadata file in the archives.

**Comment by fbergmann** [comment]
It is perfectly valid to have multiple metadata files

**Comment by matthiaskoenig** [comment]
Yes, is valid.

Just wanted to be able to collect everything in one file. Not required for the L1V3 release, this will just makes things easier on my side. 
Most of the people will look at the archives with a zip tool. Having only one metadata file in there, makes it more convenient than having to look at 10 different ones.
