### ISSUE TITLE
Restrict subtasks in listOfSubtasks

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#60]
Just writing this down so I don't forget.

We should restrict the allowed subtasks in the list of subtasks to avoid mixing of repeatedTasks with tasks: I.e. If more than one `subtask` exists in the `listOfSubTasks` in a `repeatedTask` than all subtasks must be subclasses of `Task`, i.e. no mixing of `repeatedTasks` with `tasks` is allowed in the `listOfSubTasks`.
The mixing creates a multitude of problems, like: how to combine the data from the simple tasks and repeated tasks (because data of multiple subtasks must be appended).

I.e. this is not allowed:
```
<task id=task0 />
<task id=task1 />

<repeatedTask id=repeated0 />
<listOfSubtasks>
  <subtask  task=task0 />
  <subtask task=repeated1/>
</listOfSubtasks>
</repeatedTask>

<repeatedTask id=repeated1 />
<listOfSubtasks>
  <subtask task=task1 />
</listOfSubtasks>
</repeatedTask>
```
Only such patterns
```
<task id=task0 />
<task id=task1 />

<repeatedTask id=repeated0 />
<listOfSubtasks>
  <subtask task=repeated1/>
</listOfSubtasks>
</repeatedTask>

<repeatedTask id=repeated1 />
<listOfSubtasks>
  <subtask task=task0 />
  <subtask task=task1 />
</listOfSubtasks>
</repeatedTask>
```
Currently, it is completely unclear what such mixings mean, how they should be handeled, ...
These mixings also create a lot of problems if we want to calculate summary math over the repeated tasks like mean, std, .... In addition it simplifies the handling of nested repeated tasks.

A repeated task is just a repeated execution of a task. It does not say anything about how such repeats should be combined (in my opinion they should not), and consequently they can't be appended with a simple task. 

edit: updated xml for clarification

**Comment by fbergmann** [comment]
I don't quite understand ... subtasks do not have a listofsubtasks ... or is that one of the changes of l1v4?

**Comment by matthiaskoenig** [comment]
I updated the xml. I hope this clears up what I mean.

**Comment by fbergmann** [comment]
I see ... not entirely sure why someone would write a repeatedSubtask that way ... not sure there is a reason to prohibit right away ... especially since once we addressed how we access the simulation results of a repeated subtask, it should not provide difficulty to extract the data.

**Comment by jonrkarr** [comment]
I agree that listOfSubTasks with mixed tasks and repeated tasks implies complex results. 

But, mixing of single and repeated tasks can be managed. For example, results of such mixing can be encoded into a matrix; the single task could be treated like a repeated task with a single iteration and a single sub-task. This how we've managed such mixing (prior to seeing this issue I wasn't aware of any intention to prohibit this. Consequently, I assumed that tellurium and iBioSim must support it.). As result, I don't think this has to be prohibited. I think this could be addressed with more clarity about the intended output.

Also, prohibiting such mixing wouldn't resolve all of the possible complexity in the results of repeated tasks. If mixing task types should be prohibited within a listOfSubtasks, should these scenarios also be prohibited?
- Multiple sub-tasks which are repeated tasks with different ranges of different lengths
- Sub-tasks which are single tasks of simulations of different models with time courses of different lengths

**Comment by matthiaskoenig** [comment]
I am more relaxed about this now. Frank and Jonathan convinced me here. Closing this.

**Comment by jonrkarr** [comment]
I think this is a good decision. This simplifies the implementational complexity of SED-ML. Perhaps in the future when there are better libraries and more support for SED-ML this can be relaxed.
