### ISSUE TITLE
Include SBML files locally in at least some examples

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#66]
It would be nice to have local copies of the SBML files in our example .omex combine archives.

**Comment by luciansmith** [comment]
@jonrkarr : is this done?  I feel like it may have happened along the way with the other fixes you made to the omex files.

**Comment by jonrkarr** [comment]
I didn't fix any of the examples in the SED-ML specs. I fixed the examples in sed-ml.io. I believe the SBML and CellML files are in the COMBINE archives there. Given that website, I don't think the specs need to include many complete examples.

**Comment by luciansmith** [comment]
Agreed; I'm pretty sure I was thinking of the web site when I created this issue.  Closing!
