### ISSUE TITLE
Describe sampling sensitivity analyses

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#7]
# Topic
Describing sampling sensitivity analysis.
[`https://sourceforge.net/p/sed-ml/proposals/3/`](https://sourceforge.net/p/sed-ml/proposals/3/)

# Proposal
A proposal was written up some years ago, now at
https://github.com/SED-ML/sed-ml/raw/master/specification/proposals/sampling-sensitivity-proposal/version-1/sed-ml-L1V1.pdf

**Comment by matthiaskoenig** [comment]
The proposed functionality will be covered by other core SED-ML L1V4 features.
I.e. via a combination of 
- repeatedTasks or stochastic simulations ( #22 ) the multiple runs to sample the sensitivities can be generated
- by calculating math over repeated tasks ( #53 ) the sensitivities can be calculated
Requires probably some of the clarifications of how to deal with multi-dimensional data ( #21 )

No need for an extension proposal.

**Comment by luciansmith** [comment]
Given that this already has a 'wontfix' label, I'm closing the issue.
