### ISSUE TITLE
Support global parameters of simulation experiments

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#73]
In my opinion, there's a need for global parameters of simulation experiments, which are distinct from the parameters of individual algorithms. 

Such global parameters could be represented by the existing algorithm parameter class.

Example
- Several simulation tools have the capability to execute alternative algorithms from those requested by SED-ML documents. In many cases, simulation tools execute alternate algorithms without clearly warning the user that the mathematical meaning of their simulation may be distorted. First, simulation tools should display clear warnings. Second, users should be able to control whether simulation tools can use alternative algorithms or whether KiSAO ids should be strictly interpreted. This could be treated as a global parameter of a simulation experiment. For portability among simulation tools, a KiSAO term could be created for this parameter and tools could recognize the same KiSAO term.

**Comment by matthiaskoenig** [comment]
I agree. There is a need for global AlgorithmParameters. Best example is a global random seed for the complete experiment.
I could see this even in L1V4, because it is straight forward to implement (in library, implementation and specification) and would provide direct added value.

**Comment by luciansmith** [comment]
I put the 'L2' label on this, as I don't see any way to include it in the current schema.  If I'm wrong, please update the label!

**Comment by jonrkarr** [comment]
I agree with the L2 label.

**Comment by matthiaskoenig** [comment]
Sounds good. Let's do this in L2. Removing this from the agenda for the meeting.

**Comment by luciansmith** [comment]
This was actually implemented in L1v4 after all.
