### ISSUE TITLE
Clarify the semantics of internal/relative references to models

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#80]
The specifications should more clearly describe how models whose source is defined by reference to other models in the same SED document should be interpreted. It would also be helpful to include an example.

In such cases, the underlying source file (or URL) and any model changes should be inherited from the (chain of) referenced model(s).

**Comment by matthiaskoenig** [comment]
Yes, clarification and example required in L1V4 specification. I will make a proposal.

**Comment by jonrkarr** [comment]
There are two styles of internal references floating in the community:
- `source="{id of another model}"`
- `source="#{id of another model}"`

Since these can easily be confused and most tools seem to support the latter, I propose to not support the former. The examples at http://sed-ml.io also use the later. In my opinion, the former also introduces confusion with the attributes that end in the suffix `Reference`. The later also has the advantage that `#...` more clearly indicates that this is not a reference local file.

These are the examples that would need to be revised:
- Listing 2.26:  `<model id="m0002" language="urn:sedml:language:sbml" source="m0001">`
- Listing A.1:  `<model id="model2" language="urn:sedml:language:sbml.level -3.version -1" source="model1">`
- Listing A.10:  `<model id="model2" name="Circadian Chaos" language="urn:sedml:language:sbml" source="model1">`

**Comment by luciansmith** [comment]
Fixed!
