### ISSUE TITLE
Clarify the semantics of mathematical expressions of data generators

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#82]
Related to #77, #65, and #59, the semantics of mathematical expressions of data generators could be clearer. Several things could be clearer:
- What should be done when variables have different shapes: Should the result be NaN? Should an error be thrown?
- My interpretation is that the expressions are implicitly element-wise computations. This should be more explicit, and ideally it should be possible to describe matrix computations.
- In particular, the semantics of functions such as `min` and `sum` could be clearer. These functions are particularly unclear because they are often used to reduce arrays or matrices to single values or to reduce a dimension.

**Comment by luciansmith** [comment]
I believe that in the course of fixing related issues, this issue has also been addressed.  In particular:

The MathML section now opens with:

"All the operations listed above operate on scalar values. Non-scalar values are allowed in the Math of
DataGenerator elements, where a Variable may point to multi-dimensional results from a Task or from
an external DataSource. In these cases, any MathML functionality is assumed to apply element-by-
element, either from dimensional data to a scalar, or from dimensional data to other dimensional data
with identical dimensions. In other words, if M and N are matrices, ’M+3’ would add three to every element
of M, and ’M+N’ would require that M and N have the same dimensions, and the resulting matrix R would
be created such that R(x,y) = M(x,y) + N(x,y). At this point SED-ML does not define an algebra of
vector values."

(This doesn't say what to do if the matrices don't match, but does say it's illegal.  At that point, an interpreter can do what it likes.)

The min/sum functions are now handled in DependentVariables with a KiSAO 'term'.  See the 'RemainingDimension' class for a discussion of that.

**Comment by jonrkarr** [comment]
A few suggestions for clarity:

> All the operations listed above describe functions of scalar-valued SED variables, or element-wise computations of matrix-valued SED variables. Matrix-valued SED variables can arise in multiple ways. For example, a variable for a basic task of a non-spatial uniform time course would be a vector with length equal to the number of steps of the time course plus one. A variable for a repeated task of a non-spatial time course could be represented a matrix with dimensions for the iterations of the repeated tasks, its subtasks, and the steps of the nested basic task. MathML functions for matrices should be evaluated on an element-wise basis. For example, if `M` and `N` were two 2D matrix-valued SED variables, `M+3` would add three to every element of `M`, `R = M+N` would only be valid if `M` and `N` have the same dimensions, and `R_{i,j}` would
be equal to `M_{i,j} + N_{i,j}`. At this point, SED-ML does not define an algebra for matrix computations.

**Comment by luciansmith** [comment]
Done!
