### ISSUE TITLE
`id` attribute is missing from tables 2.22-2.24 of L1V3 specs of plot2d, plot3d, report attributes

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#84]

**Comment by luciansmith** [comment]
'id' (and 'name') are part of SBase, and so are not repeated for those various classes.

The only time 'id' shows up in a class is when the class changes the attribute to be required instead of optional.

**Comment by jonrkarr** [comment]
`id` is repeated in the specs for all classes except these.

**Comment by luciansmith** [comment]
I double-checked the L1v4 spec, and indeed, the only times 'id' is repeated in a class is when it's required.
