### ISSUE TITLE
More explanation about "XPATH"s with more explicit examples would be informative

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#87]
I think the non-standard use of "XPATHs" which blend concrete XML XPATHs with implicit attribute targets is a potential source of confusion. First, these don't behave quite like true XPATHs. Second, this breaks down the abstraction barrier between SED-ML and the model languages. In my opinion, this substantially detracts from the motivation for using XPATHs. For simulation tools, the use of XPATHs also breaks the abstraction barrier between the XML serialization of models and their semantic meanings setup by libraries such as libSBML. This forces tools to be aware of the XML XPATHs of model elements in addition to their domain-specific identifiers.

I appreciate the rationale for trying to use XPATHs and the reason why strict XPATHs don't work. I suggest using clearer terminology which reflects that these are (often) not strictly XML XPATHs. I think a more detailed example and explanation would also be helpful (i.e., how amount/concentration is an implicit target suffix of `sbml:species` XPATHs, how `/@value` is often an implicit suffix of XPATHs for `sbml:parameter`).

**Comment by luciansmith** [comment]
I *think* this has now been addressed in the ComputeChange section, re: what it means when an element is referenced in a mathematical context vs. what it means when an attribute is referenced.

Unless I'm wrong, the XPaths to elements we use are correct and can indeed be considered 'strict' XPaths.  I think the problem simply was that you were expecting it to point to attributes when they point to elements instead?

**Comment by jonrkarr** [comment]
> Unless I'm wrong, the XPaths to elements we use are correct and can indeed be considered 'strict' XPaths. I think the problem simply was that you were expecting it to point to attributes when they point to elements instead?

Yes, I found this confusing because this is really a convention for the intersection of SED-ML with (specific elements of) specific model languages which I don't think was clearly stated. From an XPath perspective, I felt one would expect XPaths to point to attributes.
