### ISSUE TITLE
Decide whether to update old specs

### ISSUE THREAD

**Issue by luciansmith** [SED-ML/sed-ml#91]
In general, a new 'version' of the SED-ML specification includes two things: new features of the language, and corrections and clarifications of existing parts of the specification.

@jonrkarr has been filing some bug reports about the L1v3 spec that are concerned with the latter:  missing elements from tables, unclear descriptions, etc.

Should we make those corrections and issue an updated version of the L1v3 specification, as well as incorporating the fixes into the L1v4 spec?  Even if we should, *can* we--i.e. do we have the resources to do this, working on two or more specs at once?

**Comment by jonrkarr** [comment]
To clarify, I'm not particularly concerned with any specific version. I also don't think the L1V3 pdf needs to be changed. I think a more informal mechanism for collating clarifications and corrections is sufficient. That could even be achieved with these GitHub issues. For example, use a label to tag L1V3 clarifications/corrections and conclude each issue with a summary of the correction.

I think the need for updating L1V3 depends a lot on the timeline of the next release and when software tools will be updated to support it. If L1V4 is going to be released soon and software tools will soon support it, I don't think there's much need to focus all the older versions.

**Comment by luciansmith** [comment]
OK, that's good to hear.  In that case, you should definitely be using the L1v4 draft spec as your base to make suggestions from--there's been a ton of changes. 

As far as timing, I think if we work on it, we should be able to get the spec released this year; hopefully in time for the annual JIB issue (in March?)

**Comment by luciansmith** [comment]
Closing this--the decision was to update L1v4 only.
