### ISSUE TITLE
What are the conventions for namespaces of content of NewXML?

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#92]
The content of the NewXML examples in the L1V3 specifications outline a convention that the content of NewXML need not use use namespaces, and that simulation tools should infer their namespaces based on the target of the change. 

In the example below, simulation tools are expected to infer that the namespace of `parameter` is `sbml`. 
```xml
<newXML>
  <parameter id="V_mT_1" value="0.7" />
  <parameter id="V_mT_2" value="4.6"> />
</newXML>
```

libSED-ML supports this by reading the content of NewXML into XML nodes which have no namespace. This is distinct from how libSED-ML reads SED objects. SED objects are interpreted to have the SED-ML namespace.

However, from a strict XML perspective, I think the default namespace of the content of newXML is the default namespace of the document (in this case `sedML`, i.e. parameter should be interpreted as `sedML:parameter`). This leads to the need to infer the namespace. This breaks down the abstraction barrier between SED-ML and the model languages, which detracts from the motivation for describing changes in SED-ML (using XML) rather than in the model languages.

To alleviate this confusion and bolster the abstraction barrier, I think the content of NewXML needs to explicitly declare its namespace as illustrated below.

```xml
<newXML>
  <sbml:parameter xmlns:sbml="http://sed-ml.org/sed-ml/level1/version3" id="V_mT_1" value="0.7" />
  <sbml:parameter xmlns:sbml="http://sed-ml.org/sed-ml/level1/version3" id="V_mT_2" value="4.6"> />
</newXML>
```

**Comment by fbergmann** [comment]
indeed the `newXML` element is differently treated from the rest of the document. Its content is supposed to be in the same namespaces as the xpath target. They are not to be interpreted as the part of the SED-ML document. But it is certainly good practice to declare namespaces. And just as with the xpath query, prefixing the elements  (and indeed the attributes) seems like a good idea for best practice. 

(Just a niggle .. you used the sedml namespace uri, it has to be however the precise one that is being used from in the underlying model.)

**Comment by jonrkarr** [comment]
Thanks for the correction. The namespaces should have been "http://www.sbml.org/sbml/level3/version1".

```xml
<newXML>
  <sbml:parameter xmlns:sbml="http://www.sbml.org/sbml/level3/version1" id="V_mT_1" value="0.7" />
  <sbml:parameter xmlns:sbml="http://www.sbml.org/sbml/level3/version1" id="V_mT_2" value="4.6" />
</newXML>
```

**Comment by luciansmith** [comment]
Is this suggestion merely to change the examples?  Or is a corresponding change in the text warranted?

**Comment by jonrkarr** [comment]
The examples need to be corrected. I think a note about namespaces in the section of the specs on NewXML would also be helpful.

**Comment by luciansmith** [comment]
The examples are now fixed, and the newXML description now reads (in part):

"NewXML must hold a valid piece of XML *in the appropriate namespace* which after insertion into the original model must result in a valid model file"
