### ISSUE TITLE
Encourage the labels of data sets to be unique within a report

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#93]
The specs say the labels of datasets should be "unambiguous". This generic guidance should apply to all ids of all elements of SED documents.

To facilitate further machine interpretation of reports, I think it would be helpful to provide more specific guidance -- encourage the labels of data sets to be unique within each report (i.e., table should have unique row labels). This would be mean that each tuple of (report.id, dataset.label) should be unique within a SED document.

**Comment by matthiaskoenig** [comment]
I agree.

**Comment by matthiaskoenig** [comment]
Just to clarify. This is the current behavior. I.e. the tuple (`report.id, dataset.label`) is unique. A clarification sentence will be added to the specification

**Comment by jonrkarr** [comment]
Ids alone are unique. The issue is that reports are encouraged to be exported only using labels (which are not unique) for column headings. 

This problem could also be addressed by putting more metadata into exported versions of reports. However, CSV has limited ability to capture metadata. A simple solution that works even for CSV is for labels to be unique within reports.

**Comment by jonrkarr** [comment]
Closing because this has been edited into the draft specs for L1V4.
